//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//
//     Changes in this file may cause incorrect behavior and will be lost if
//     the code is rebuilt.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moway.Project.GraphicProject.Forms {
    using System;
    
    
    /// <summary>
    ///  Strongly typed resource class, to search for translated strings, etc.
    /// </summary>
    // StronglyTypedResourceBuilder automatically generated this class
    //  through a tool such as ResGen or Visual Studio.
    // To add or remove a member, edit the .ResX file and then run ResGen again
    // with the / str option or recompile your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VariablesMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VariablesMessages() {
        }
        
        /// <summary>
        ///  Returns the ResourceManager instance cached used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moway.Project.GraphicProject.Forms.VariablesMessages", typeof(VariablesMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Replaces the CurrentUICulture property of the current thread
        ///   for all resource searches using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Delete Variable.
        /// </summary>
        internal static string DELETE_VARIABLE {
            get {
                return ResourceManager.GetString("DELETE_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Edit Variable.
        /// </summary>
        internal static string EDIT_VARIABLE {
            get {
                return ResourceManager.GetString("EDIT_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Make sure the name consists only of the letters a-z, A-Z, 0-9..
        /// </summary>
        internal static string NAME_CONDITIONS {
            get {
                return ResourceManager.GetString("NAME_CONDITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Please choose a different name for the variable..
        /// </summary>
        internal static string NAME_ERROR {
            get {
                return ResourceManager.GetString("NAME_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to This word is a keyword for application. It is not a valid name..
        /// </summary>
        internal static string NAME_KEYWORD {
            get {
                return ResourceManager.GetString("NAME_KEYWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to New Variable.
        /// </summary>
        internal static string NEW_VARIABLE {
            get {
                return ResourceManager.GetString("NEW_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to This variable already exists in this project..
        /// </summary>
        internal static string VARIABLE_EXISTS {
            get {
                return ResourceManager.GetString("VARIABLE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Selected variable is used in the diagram. You can not delete it..
        /// </summary>
        internal static string VARIABLE_IN_USE {
            get {
                return ResourceManager.GetString("VARIABLE_IN_USE", resourceCulture);
            }
        }
    }
}
