namespace Moway.Project.GraphicProject.Actions.AssignAccelerometer
{
    partial class AssignAccelerometerPanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AssignAccelerometerPanel));
            this.cbAssignVariable = new Moway.Template.Controls.MowayComboBox();
            this.rbXAxis = new Moway.Template.Controls.MowayRadioButton();
            this.rbYAxis = new Moway.Template.Controls.MowayRadioButton();
            this.rbZAxis = new Moway.Template.Controls.MowayRadioButton();
            this.lVariable = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // lActionName
            // 
            resources.ApplyResources(this.lActionName, "lActionName");
            // 
            // cbAssignVariable
            // 
            this.cbAssignVariable.BackColor = System.Drawing.Color.White;
            this.cbAssignVariable.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbAssignVariable.DropDownHeight = 100;
            this.cbAssignVariable.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbAssignVariable, "cbAssignVariable");
            this.cbAssignVariable.FormattingEnabled = true;
            this.cbAssignVariable.Name = "cbAssignVariable";
            this.cbAssignVariable.SelectedIndexChanged += new System.EventHandler(this.CbAssignVariable_SelectedIndexChanged);
            // 
            // rbXAxis
            // 
            resources.ApplyResources(this.rbXAxis, "rbXAxis");
            this.rbXAxis.Checked = true;
            this.rbXAxis.Name = "rbXAxis";
            this.rbXAxis.TabStop = true;
            this.rbXAxis.UseVisualStyleBackColor = true;
            this.rbXAxis.CheckedChanged += new System.EventHandler(this.RbAxis_CheckedChanged);
            // 
            // rbYAxis
            // 
            resources.ApplyResources(this.rbYAxis, "rbYAxis");
            this.rbYAxis.Name = "rbYAxis";
            this.rbYAxis.TabStop = true;
            this.rbYAxis.UseVisualStyleBackColor = true;
            this.rbYAxis.CheckedChanged += new System.EventHandler(this.RbAxis_CheckedChanged);
            // 
            // rbZAxis
            // 
            resources.ApplyResources(this.rbZAxis, "rbZAxis");
            this.rbZAxis.Name = "rbZAxis";
            this.rbZAxis.TabStop = true;
            this.rbZAxis.UseVisualStyleBackColor = true;
            this.rbZAxis.CheckedChanged += new System.EventHandler(this.RbAxis_CheckedChanged);
            // 
            // lVariable
            // 
            resources.ApplyResources(this.lVariable, "lVariable");
            this.lVariable.Name = "lVariable";
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // AssignAccelerometerPanel
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.lVariable);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.cbAssignVariable);
            this.Controls.Add(this.rbXAxis);
            this.Controls.Add(this.rbZAxis);
            this.Controls.Add(this.rbYAxis);
            resources.ApplyResources(this, "$this");
            this.Name = "AssignAccelerometerPanel";
            this.Controls.SetChildIndex(this.rbYAxis, 0);
            this.Controls.SetChildIndex(this.rbZAxis, 0);
            this.Controls.SetChildIndex(this.rbXAxis, 0);
            this.Controls.SetChildIndex(this.cbAssignVariable, 0);
            this.Controls.SetChildIndex(this.label1, 0);
            this.Controls.SetChildIndex(this.lVariable, 0);
            this.Controls.SetChildIndex(this.lActionName, 0);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Moway.Template.Controls.MowayComboBox cbAssignVariable;
        private Moway.Template.Controls.MowayRadioButton rbXAxis;
        private Moway.Template.Controls.MowayRadioButton rbYAxis;
        private Moway.Template.Controls.MowayRadioButton rbZAxis;
        private System.Windows.Forms.Label lVariable;
        private System.Windows.Forms.Label label1;
    }
}
