namespace Moway.Project.GraphicProject.Actions.Call
{
    partial class CallPanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CallPanel));
            this.lVariable = new System.Windows.Forms.Label();
            this.cbAsignVariable = new Moway.Template.Controls.MowayComboBox();
            this.label1 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // lActionName
            // 
            resources.ApplyResources(this.lActionName, "lActionName");
            // 
            // lVariable
            // 
            resources.ApplyResources(this.lVariable, "lVariable");
            this.lVariable.Name = "lVariable";
            // 
            // cbAsignVariable
            // 
            this.cbAsignVariable.BackColor = System.Drawing.Color.White;
            this.cbAsignVariable.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbAsignVariable.DropDownHeight = 100;
            this.cbAsignVariable.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbAsignVariable, "cbAsignVariable");
            this.cbAsignVariable.FormattingEnabled = true;
            this.cbAsignVariable.Name = "cbAsignVariable";
            this.cbAsignVariable.SelectedIndexChanged += new System.EventHandler(this.CbAsignVariable_SelectedIndexChanged);
            // 
            // label1
            // 
            this.label1.BackColor = System.Drawing.Color.White;
            this.label1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // CallPanel
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.label1);
            this.Controls.Add(this.lVariable);
            this.Controls.Add(this.cbAsignVariable);
            resources.ApplyResources(this, "$this");
            this.Name = "CallPanel";
            this.Controls.SetChildIndex(this.lActionName, 0);
            this.Controls.SetChildIndex(this.cbAsignVariable, 0);
            this.Controls.SetChildIndex(this.lVariable, 0);
            this.Controls.SetChildIndex(this.label1, 0);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label lVariable;
        private Moway.Template.Controls.MowayComboBox cbAsignVariable;
        private System.Windows.Forms.Label label1;
    }
}
