namespace Moway.Project.GraphicProject.Controls
{
    partial class ToolGroupPanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.toolTip = new Moway.Template.Controls.MowayToolTip();
            this.SuspendLayout();
            // 
            // GroupPanel
            // 
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "GroupPanel";
            this.Size = new System.Drawing.Size(152, 150);
            this.ResumeLayout(false);

        }

        #endregion

        private Moway.Template.Controls.MowayToolTip toolTip;


    }
}
