namespace Moway.Project.GraphicProject.Actions.CheckIn
{
    partial class CheckInPanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CheckInPanel));
            this.rbLine5 = new Moway.Template.Controls.MowayRadioButton();
            this.rbLine1 = new Moway.Template.Controls.MowayRadioButton();
            this.rbLine2 = new Moway.Template.Controls.MowayRadioButton();
            this.rbLine3 = new Moway.Template.Controls.MowayRadioButton();
            this.rbLine4 = new Moway.Template.Controls.MowayRadioButton();
            this.rbLine0 = new Moway.Template.Controls.MowayRadioButton();
            this.cbOperator = new Moway.Template.Controls.MowayComboBox();
            this.cbLineValue = new Moway.Template.Controls.MowayComboBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // lActionName
            // 
            resources.ApplyResources(this.lActionName, "lActionName");
            // 
            // rbLine5
            // 
            resources.ApplyResources(this.rbLine5, "rbLine5");
            this.rbLine5.Name = "rbLine5";
            this.rbLine5.UseVisualStyleBackColor = true;
            this.rbLine5.CheckedChanged += new System.EventHandler(this.RbLine_CheckedChanged);
            // 
            // rbLine1
            // 
            resources.ApplyResources(this.rbLine1, "rbLine1");
            this.rbLine1.Name = "rbLine1";
            this.rbLine1.UseVisualStyleBackColor = true;
            this.rbLine1.CheckedChanged += new System.EventHandler(this.RbLine_CheckedChanged);
            // 
            // rbLine2
            // 
            resources.ApplyResources(this.rbLine2, "rbLine2");
            this.rbLine2.Name = "rbLine2";
            this.rbLine2.UseVisualStyleBackColor = true;
            this.rbLine2.CheckedChanged += new System.EventHandler(this.RbLine_CheckedChanged);
            // 
            // rbLine3
            // 
            resources.ApplyResources(this.rbLine3, "rbLine3");
            this.rbLine3.Name = "rbLine3";
            this.rbLine3.UseVisualStyleBackColor = true;
            this.rbLine3.CheckedChanged += new System.EventHandler(this.RbLine_CheckedChanged);
            // 
            // rbLine4
            // 
            resources.ApplyResources(this.rbLine4, "rbLine4");
            this.rbLine4.Name = "rbLine4";
            this.rbLine4.UseVisualStyleBackColor = true;
            this.rbLine4.CheckedChanged += new System.EventHandler(this.RbLine_CheckedChanged);
            // 
            // rbLine0
            // 
            resources.ApplyResources(this.rbLine0, "rbLine0");
            this.rbLine0.Checked = true;
            this.rbLine0.Name = "rbLine0";
            this.rbLine0.TabStop = true;
            this.rbLine0.UseVisualStyleBackColor = true;
            this.rbLine0.CheckedChanged += new System.EventHandler(this.RbLine_CheckedChanged);
            // 
            // cbOperator
            // 
            this.cbOperator.BackColor = System.Drawing.Color.White;
            this.cbOperator.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbOperator.DropDownHeight = 100;
            this.cbOperator.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbOperator, "cbOperator");
            this.cbOperator.FormattingEnabled = true;
            this.cbOperator.Items.AddRange(new object[] {
            resources.GetString("cbOperator.Items"),
            resources.GetString("cbOperator.Items1")});
            this.cbOperator.Name = "cbOperator";
            this.cbOperator.SelectedIndexChanged += new System.EventHandler(this.CbOperator_SelectedIndexChanged);
            // 
            // cbLineValue
            // 
            this.cbLineValue.BackColor = System.Drawing.Color.White;
            this.cbLineValue.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbLineValue.DropDownHeight = 100;
            this.cbLineValue.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbLineValue, "cbLineValue");
            this.cbLineValue.FormattingEnabled = true;
            this.cbLineValue.Items.AddRange(new object[] {
            resources.GetString("cbLineValue.Items"),
            resources.GetString("cbLineValue.Items1")});
            this.cbLineValue.Name = "cbLineValue";
            this.cbLineValue.SelectedIndexChanged += new System.EventHandler(this.CbLineValue_SelectedIndexChanged);
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // label2
            // 
            resources.ApplyResources(this.label2, "label2");
            this.label2.Name = "label2";
            // 
            // label3
            // 
            resources.ApplyResources(this.label3, "label3");
            this.label3.Name = "label3";
            // 
            // CheckInPanel
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.rbLine5);
            this.Controls.Add(this.rbLine1);
            this.Controls.Add(this.rbLine2);
            this.Controls.Add(this.rbLine3);
            this.Controls.Add(this.rbLine4);
            this.Controls.Add(this.rbLine0);
            this.Controls.Add(this.cbOperator);
            this.Controls.Add(this.cbLineValue);
            this.Name = "CheckInPanel";
            resources.ApplyResources(this, "$this");
            this.Controls.SetChildIndex(this.lActionName, 0);
            this.Controls.SetChildIndex(this.cbLineValue, 0);
            this.Controls.SetChildIndex(this.cbOperator, 0);
            this.Controls.SetChildIndex(this.rbLine0, 0);
            this.Controls.SetChildIndex(this.rbLine4, 0);
            this.Controls.SetChildIndex(this.rbLine3, 0);
            this.Controls.SetChildIndex(this.rbLine2, 0);
            this.Controls.SetChildIndex(this.rbLine1, 0);
            this.Controls.SetChildIndex(this.rbLine5, 0);
            this.Controls.SetChildIndex(this.label1, 0);
            this.Controls.SetChildIndex(this.label2, 0);
            this.Controls.SetChildIndex(this.label3, 0);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Moway.Template.Controls.MowayRadioButton rbLine5;
        private Moway.Template.Controls.MowayRadioButton rbLine1;
        private Moway.Template.Controls.MowayRadioButton rbLine2;
        private Moway.Template.Controls.MowayRadioButton rbLine3;
        private Moway.Template.Controls.MowayRadioButton rbLine4;
        private Moway.Template.Controls.MowayRadioButton rbLine0;
        private Moway.Template.Controls.MowayComboBox cbOperator;
        private Moway.Template.Controls.MowayComboBox cbLineValue;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
    }
}
