namespace Moway.Template
{
    partial class MowayBox
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MowayBox));
            this.lTittle = new System.Windows.Forms.Label();
            this.pbRight = new System.Windows.Forms.PictureBox();
            this.pbBottomLeft = new System.Windows.Forms.PictureBox();
            this.pbBottom = new System.Windows.Forms.PictureBox();
            this.pbBottomRight = new System.Windows.Forms.PictureBox();
            this.pbLeft = new System.Windows.Forms.PictureBox();
            this.pbTopRight = new System.Windows.Forms.PictureBox();
            this.pbTop = new System.Windows.Forms.PictureBox();
            this.pbTopLeft = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.pbRight)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottomLeft)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottom)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottomRight)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbLeft)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTopRight)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTop)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTopLeft)).BeginInit();
            this.SuspendLayout();
            // 
            // lTittle
            // 
            resources.ApplyResources(this.lTittle, "lTittle");
            this.lTittle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(207)))), ((int)(((byte)(207)))));
            this.lTittle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(72)))), ((int)(((byte)(138)))));
            this.lTittle.Name = "lTittle";
            // 
            // pbRight
            // 
            resources.ApplyResources(this.pbRight, "pbRight");
            this.pbRight.Name = "pbRight";
            this.pbRight.TabStop = false;
            // 
            // pbBottomLeft
            // 
            resources.ApplyResources(this.pbBottomLeft, "pbBottomLeft");
            this.pbBottomLeft.Name = "pbBottomLeft";
            this.pbBottomLeft.TabStop = false;
            // 
            // pbBottom
            // 
            resources.ApplyResources(this.pbBottom, "pbBottom");
            this.pbBottom.Name = "pbBottom";
            this.pbBottom.TabStop = false;
            // 
            // pbBottomRight
            // 
            resources.ApplyResources(this.pbBottomRight, "pbBottomRight");
            this.pbBottomRight.Name = "pbBottomRight";
            this.pbBottomRight.TabStop = false;
            // 
            // pbLeft
            // 
            resources.ApplyResources(this.pbLeft, "pbLeft");
            this.pbLeft.Name = "pbLeft";
            this.pbLeft.TabStop = false;
            // 
            // pbTopRight
            // 
            resources.ApplyResources(this.pbTopRight, "pbTopRight");
            this.pbTopRight.Name = "pbTopRight";
            this.pbTopRight.TabStop = false;
            // 
            // pbTop
            // 
            resources.ApplyResources(this.pbTop, "pbTop");
            this.pbTop.Name = "pbTop";
            this.pbTop.TabStop = false;
            // 
            // pbTopLeft
            // 
            resources.ApplyResources(this.pbTopLeft, "pbTopLeft");
            this.pbTopLeft.Name = "pbTopLeft";
            this.pbTopLeft.TabStop = false;
            // 
            // MowayBox
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(234)))), ((int)(((byte)(234)))));
            this.Controls.Add(this.pbRight);
            this.Controls.Add(this.lTittle);
            this.Controls.Add(this.pbBottomLeft);
            this.Controls.Add(this.pbBottom);
            this.Controls.Add(this.pbBottomRight);
            this.Controls.Add(this.pbLeft);
            this.Controls.Add(this.pbTopRight);
            this.Controls.Add(this.pbTop);
            this.Controls.Add(this.pbTopLeft);
            resources.ApplyResources(this, "$this");
            this.Name = "MowayBox";
            ((System.ComponentModel.ISupportInitialize)(this.pbRight)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottomLeft)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottom)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottomRight)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbLeft)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTopRight)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTop)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTopLeft)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        protected System.Windows.Forms.Label lTittle;
        protected System.Windows.Forms.PictureBox pbBottom;
        protected System.Windows.Forms.PictureBox pbLeft;
        protected System.Windows.Forms.PictureBox pbTopRight;
        protected System.Windows.Forms.PictureBox pbTop;
        protected System.Windows.Forms.PictureBox pbTopLeft;
        protected System.Windows.Forms.PictureBox pbRight;
        protected System.Windows.Forms.PictureBox pbBottomRight;
        protected System.Windows.Forms.PictureBox pbBottomLeft;
    }
}
