//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//
//     Changes in this file may cause incorrect behavior and will be lost if
//     the code is rebuilt.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moway.Project.GraphicProject.GraphLayout.Elements {
    using System;
    
    
    /// <summary>
    ///  Strongly typed resource class, to search for translated strings, etc.
    /// </summary>
    // StronglyTypedResourceBuilder automatically generated this class
    //  through a tool such as ResGen or Visual Studio.
    // To add or remove a member, edit the .ResX file and then run ResGen again
    // with the / str option or recompile your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ArrowGraphics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArrowGraphics() {
        }
        
        /// <summary>
        ///  Returns the ResourceManager instance cached used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moway.Project.GraphicProject.GraphLayout.Elements.ArrowGraphics", typeof(ArrowGraphics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Replaces the CurrentUICulture property of the current thread
        ///   for all resource searches using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CornerBottomLeftGraphic {
            get {
                object obj = ResourceManager.GetObject("CornerBottomLeftGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CornerBottomLeftGraphicSelected {
            get {
                object obj = ResourceManager.GetObject("CornerBottomLeftGraphicSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CornerBottomRightGraphic {
            get {
                object obj = ResourceManager.GetObject("CornerBottomRightGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CornerBottomRightGraphicSelected {
            get {
                object obj = ResourceManager.GetObject("CornerBottomRightGraphicSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CornerTopLeftGraphic {
            get {
                object obj = ResourceManager.GetObject("CornerTopLeftGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CornerTopLeftGraphicSelected {
            get {
                object obj = ResourceManager.GetObject("CornerTopLeftGraphicSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CornerTopRightGraphic {
            get {
                object obj = ResourceManager.GetObject("CornerTopRightGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CornerTopRightGraphicSelected {
            get {
                object obj = ResourceManager.GetObject("CornerTopRightGraphicSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EndBottomGraphic {
            get {
                object obj = ResourceManager.GetObject("EndBottomGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EndBottomGraphicSelected {
            get {
                object obj = ResourceManager.GetObject("EndBottomGraphicSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EndLeftGraphic {
            get {
                object obj = ResourceManager.GetObject("EndLeftGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EndLeftGraphicSelected {
            get {
                object obj = ResourceManager.GetObject("EndLeftGraphicSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EndRightGraphic {
            get {
                object obj = ResourceManager.GetObject("EndRightGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EndRightGraphicSelected {
            get {
                object obj = ResourceManager.GetObject("EndRightGraphicSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EndTopGraphic {
            get {
                object obj = ResourceManager.GetObject("EndTopGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EndTopGraphicSelected {
            get {
                object obj = ResourceManager.GetObject("EndTopGraphicSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LineHorizontalGraphic {
            get {
                object obj = ResourceManager.GetObject("LineHorizontalGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LineHorizontalGraphicSelected {
            get {
                object obj = ResourceManager.GetObject("LineHorizontalGraphicSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LineVerticalGraphic {
            get {
                object obj = ResourceManager.GetObject("LineVerticalGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LineVerticalGraphicSelected {
            get {
                object obj = ResourceManager.GetObject("LineVerticalGraphicSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartBottomGraphic {
            get {
                object obj = ResourceManager.GetObject("StartBottomGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartBottomGraphicSelected {
            get {
                object obj = ResourceManager.GetObject("StartBottomGraphicSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartLeftGraphic {
            get {
                object obj = ResourceManager.GetObject("StartLeftGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartLeftGraphicSelected {
            get {
                object obj = ResourceManager.GetObject("StartLeftGraphicSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartRightGraphic {
            get {
                object obj = ResourceManager.GetObject("StartRightGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartRightGraphicSelected {
            get {
                object obj = ResourceManager.GetObject("StartRightGraphicSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartTopGraphic {
            get {
                object obj = ResourceManager.GetObject("StartTopGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Search for an adapted resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartTopGraphicSelected {
            get {
                object obj = ResourceManager.GetObject("StartTopGraphicSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
