namespace Moway.Project.GraphicProject.Actions
{
    partial class ActionPanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.lActionName = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // lActionName
            // 
            this.lActionName.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lActionName.Location = new System.Drawing.Point(0, 5);
            this.lActionName.Name = "lActionName";
            this.lActionName.Size = new System.Drawing.Size(220, 15);
            this.lActionName.TabIndex = 0;
            this.lActionName.Text = "Action type";
            this.lActionName.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // ActionPanel
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(234)))), ((int)(((byte)(234)))));
            this.Controls.Add(this.lActionName);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "ActionPanel";
            this.Size = new System.Drawing.Size(220, 150);
            this.Load += new System.EventHandler(this.ActionPanel_Load);
            this.ResumeLayout(false);

        }

        #endregion

        protected System.Windows.Forms.Label lActionName;

    }
}
