//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//
//     Changes in this file may cause incorrect behavior and will be lost if
//     the code is rebuilt.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moway.Project.GraphicProject.Actions {
    using System;
    
    
    /// <summary>
    ///  Strongly typed resource class, to search for translated strings, etc.
    /// </summary>
    // StronglyTypedResourceBuilder automatically generated this class
    //  through a tool such as ResGen or Visual Studio.
    // To add or remove a member, edit the .ResX file and then run ResGen again
    // with the / str option or recompile your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompareMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompareMessages() {
        }
        
        /// <summary>
        ///  Returns the ResourceManager instance cached used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moway.Project.GraphicProject.Actions.CompareMessages", typeof(CompareMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Replaces the CurrentUICulture property of the current thread
        ///   for all resource searches using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to bigger than.
        /// </summary>
        internal static string BIGGER {
            get {
                return ResourceManager.GetString("BIGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to bigger than or equal to.
        /// </summary>
        internal static string BIGGER_OR_EQUAL {
            get {
                return ResourceManager.GetString("BIGGER_OR_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to different from.
        /// </summary>
        internal static string DISTINCT {
            get {
                return ResourceManager.GetString("DISTINCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to equal to.
        /// </summary>
        internal static string EQUAL {
            get {
                return ResourceManager.GetString("EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to False.
        /// </summary>
        internal static string FALSE {
            get {
                return ResourceManager.GetString("FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to If.
        /// </summary>
        internal static string IF {
            get {
                return ResourceManager.GetString("IF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to is.
        /// </summary>
        internal static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Otherwise..
        /// </summary>
        internal static string OTHERWISE {
            get {
                return ResourceManager.GetString("OTHERWISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to smaller than.
        /// </summary>
        internal static string SMALLER {
            get {
                return ResourceManager.GetString("SMALLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to smaller than or equal to.
        /// </summary>
        internal static string SMALLER_OR_EQUAL {
            get {
                return ResourceManager.GetString("SMALLER_OR_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to True.
        /// </summary>
        internal static string TRUE {
            get {
                return ResourceManager.GetString("TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to the value of.
        /// </summary>
        internal static string VALUE_OF {
            get {
                return ResourceManager.GetString("VALUE_OF", resourceCulture);
            }
        }
    }
}
