namespace Moway.Project.GraphicProject.Actions.AssignLine
{
    partial class AssignLinePanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AssignLinePanel));
            this.lVariable = new System.Windows.Forms.Label();
            this.cbAssignVariable = new Moway.Template.Controls.MowayComboBox();
            this.rbRightSensor = new Moway.Template.Controls.MowayRadioButton();
            this.rbLeftSensor = new Moway.Template.Controls.MowayRadioButton();
            this.label1 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // lActionName
            // 
            resources.ApplyResources(this.lActionName, "lActionName");
            // 
            // lVariable
            // 
            resources.ApplyResources(this.lVariable, "lVariable");
            this.lVariable.Name = "lVariable";
            // 
            // cbAssignVariable
            // 
            this.cbAssignVariable.BackColor = System.Drawing.Color.White;
            this.cbAssignVariable.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbAssignVariable.DropDownHeight = 100;
            this.cbAssignVariable.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbAssignVariable, "cbAssignVariable");
            this.cbAssignVariable.FormattingEnabled = true;
            this.cbAssignVariable.Name = "cbAssignVariable";
            this.cbAssignVariable.SelectedIndexChanged += new System.EventHandler(this.CbAssignVariable_SelectedIndexChanged);
            // 
            // rbRightSensor
            // 
            resources.ApplyResources(this.rbRightSensor, "rbRightSensor");
            this.rbRightSensor.Checked = true;
            this.rbRightSensor.Name = "rbRightSensor";
            this.rbRightSensor.TabStop = true;
            this.rbRightSensor.UseVisualStyleBackColor = true;
            this.rbRightSensor.CheckedChanged += new System.EventHandler(this.RbSensor_CheckedChanged);
            // 
            // rbLeftSensor
            // 
            resources.ApplyResources(this.rbLeftSensor, "rbLeftSensor");
            this.rbLeftSensor.Name = "rbLeftSensor";
            this.rbLeftSensor.TabStop = true;
            this.rbLeftSensor.UseVisualStyleBackColor = true;
            this.rbLeftSensor.CheckedChanged += new System.EventHandler(this.RbSensor_CheckedChanged);
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // AssignLinePanel
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.label1);
            this.Controls.Add(this.lVariable);
            this.Controls.Add(this.cbAssignVariable);
            this.Controls.Add(this.rbRightSensor);
            this.Controls.Add(this.rbLeftSensor);
            this.Name = "AssignLinePanel";
            resources.ApplyResources(this, "$this");
            this.Controls.SetChildIndex(this.lActionName, 0);
            this.Controls.SetChildIndex(this.rbLeftSensor, 0);
            this.Controls.SetChildIndex(this.rbRightSensor, 0);
            this.Controls.SetChildIndex(this.cbAssignVariable, 0);
            this.Controls.SetChildIndex(this.lVariable, 0);
            this.Controls.SetChildIndex(this.label1, 0);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label lVariable;
        private Moway.Template.Controls.MowayComboBox cbAssignVariable;
        private Moway.Template.Controls.MowayRadioButton rbRightSensor;
        private Moway.Template.Controls.MowayRadioButton rbLeftSensor;
        private System.Windows.Forms.Label label1;
    }
}
