namespace Moway.Project.GraphicProject.Actions.Straight
{
    partial class StraightPanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(StraightPanel));
            this.lSpeed = new System.Windows.Forms.Label();
            this.rbForward = new Moway.Template.Controls.MowayRadioButton();
            this.nudSpeed = new Moway.Template.Controls.MowayNumericUpDown();
            this.lSpeedRange = new System.Windows.Forms.Label();
            this.rbBackward = new Moway.Template.Controls.MowayRadioButton();
            this.cbSpeed = new Moway.Template.Controls.MowayComboBox();
            this.lDirection = new System.Windows.Forms.Label();
            this.lFlowchart = new System.Windows.Forms.Label();
            this.rbContiniously = new Moway.Template.Controls.MowayRadioButton();
            this.rbDistance = new Moway.Template.Controls.MowayRadioButton();
            this.cbTime = new Moway.Template.Controls.MowayComboBox();
            this.cbDistance = new Moway.Template.Controls.MowayComboBox();
            this.nudTime = new Moway.Template.Controls.MowayNumericUpDown();
            this.nudDistance = new Moway.Template.Controls.MowayNumericUpDown();
            this.rbTime = new Moway.Template.Controls.MowayRadioButton();
            this.lTimeRange = new System.Windows.Forms.Label();
            this.lDistanceRange = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.cbFinishCommands = new Moway.Template.Controls.MowayCheckBox();
            this.panel2 = new System.Windows.Forms.Panel();
            this.panel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // lActionName
            // 
            resources.ApplyResources(this.lActionName, "lActionName");
            // 
            // lSpeed
            // 
            resources.ApplyResources(this.lSpeed, "lSpeed");
            this.lSpeed.Name = "lSpeed";
            // 
            // rbForward
            // 
            resources.ApplyResources(this.rbForward, "rbForward");
            this.rbForward.Checked = true;
            this.rbForward.Name = "rbForward";
            this.rbForward.TabStop = true;
            this.rbForward.UseVisualStyleBackColor = true;
            this.rbForward.CheckedChanged += new System.EventHandler(this.RbForward_CheckedChanged);
            // 
            // nudSpeed
            // 
            this.nudSpeed.BackColor = System.Drawing.Color.White;
            this.nudSpeed.DecimalPlaces = 0;
            resources.ApplyResources(this.nudSpeed, "nudSpeed");
            this.nudSpeed.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudSpeed.Maximum = new decimal(new int[] {
            100,
            0,
            0,
            0});
            this.nudSpeed.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudSpeed.Name = "nudSpeed";
            this.nudSpeed.Value = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudSpeed.ValueChanged += new System.EventHandler(this.NudValue_ValueChanged);
            // 
            // lSpeedRange
            // 
            resources.ApplyResources(this.lSpeedRange, "lSpeedRange");
            this.lSpeedRange.Name = "lSpeedRange";
            // 
            // rbBackward
            // 
            resources.ApplyResources(this.rbBackward, "rbBackward");
            this.rbBackward.Name = "rbBackward";
            this.rbBackward.UseVisualStyleBackColor = true;
            // 
            // cbSpeed
            // 
            this.cbSpeed.BackColor = System.Drawing.Color.White;
            this.cbSpeed.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbSpeed.DropDownHeight = 100;
            this.cbSpeed.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbSpeed, "cbSpeed");
            this.cbSpeed.FormattingEnabled = true;
            this.cbSpeed.Items.AddRange(new object[] {
            resources.GetString("cbSpeed.Items")});
            this.cbSpeed.Name = "cbSpeed";
            this.cbSpeed.SelectedIndexChanged += new System.EventHandler(this.CbSpeed_SelectedIndexChanged);
            // 
            // lDirection
            // 
            resources.ApplyResources(this.lDirection, "lDirection");
            this.lDirection.Name = "lDirection";
            // 
            // lFlowchart
            // 
            resources.ApplyResources(this.lFlowchart, "lFlowchart");
            this.lFlowchart.Name = "lFlowchart";
            // 
            // rbContiniously
            // 
            resources.ApplyResources(this.rbContiniously, "rbContiniously");
            this.rbContiniously.Checked = true;
            this.rbContiniously.Name = "rbContiniously";
            this.rbContiniously.TabStop = true;
            this.rbContiniously.UseVisualStyleBackColor = true;
            this.rbContiniously.CheckedChanged += new System.EventHandler(this.RbContiniously_CheckedChanged);
            // 
            // rbDistance
            // 
            resources.ApplyResources(this.rbDistance, "rbDistance");
            this.rbDistance.Name = "rbDistance";
            this.rbDistance.UseVisualStyleBackColor = true;
            this.rbDistance.CheckedChanged += new System.EventHandler(this.RbDistance_CheckedChanged);
            // 
            // cbTime
            // 
            this.cbTime.BackColor = System.Drawing.Color.White;
            this.cbTime.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbTime.DropDownHeight = 100;
            this.cbTime.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbTime, "cbTime");
            this.cbTime.FormattingEnabled = true;
            this.cbTime.Items.AddRange(new object[] {
            resources.GetString("cbTime.Items")});
            this.cbTime.Name = "cbTime";
            this.cbTime.SelectedIndexChanged += new System.EventHandler(this.CbTime_SelectedIndexChanged);
            // 
            // cbDistance
            // 
            this.cbDistance.BackColor = System.Drawing.Color.White;
            this.cbDistance.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbDistance.DropDownHeight = 100;
            this.cbDistance.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbDistance, "cbDistance");
            this.cbDistance.FormattingEnabled = true;
            this.cbDistance.Items.AddRange(new object[] {
            resources.GetString("cbDistance.Items")});
            this.cbDistance.Name = "cbDistance";
            this.cbDistance.SelectedIndexChanged += new System.EventHandler(this.CbDistance_SelectedIndexChanged);
            // 
            // nudTime
            // 
            this.nudTime.BackColor = System.Drawing.Color.White;
            this.nudTime.DecimalPlaces = 1;
            resources.ApplyResources(this.nudTime, "nudTime");
            this.nudTime.Increment = new decimal(new int[] {
            1,
            0,
            0,
            65536});
            this.nudTime.Maximum = new decimal(new int[] {
            255,
            0,
            0,
            65536});
            this.nudTime.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            65536});
            this.nudTime.Name = "nudTime";
            this.nudTime.Value = new decimal(new int[] {
            1,
            0,
            0,
            65536});
            this.nudTime.ValueChanged += new System.EventHandler(this.NudValue_ValueChanged);
            // 
            // nudDistance
            // 
            this.nudDistance.BackColor = System.Drawing.Color.White;
            this.nudDistance.DecimalPlaces = 1;
            resources.ApplyResources(this.nudDistance, "nudDistance");
            this.nudDistance.Increment = new decimal(new int[] {
            1,
            0,
            0,
            65536});
            this.nudDistance.Maximum = new decimal(new int[] {
            255,
            0,
            0,
            65536});
            this.nudDistance.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            65536});
            this.nudDistance.Name = "nudDistance";
            this.nudDistance.Value = new decimal(new int[] {
            1,
            0,
            0,
            65536});
            this.nudDistance.ValueChanged += new System.EventHandler(this.NudValue_ValueChanged);
            // 
            // rbTime
            // 
            resources.ApplyResources(this.rbTime, "rbTime");
            this.rbTime.Name = "rbTime";
            this.rbTime.UseVisualStyleBackColor = true;
            this.rbTime.CheckedChanged += new System.EventHandler(this.RbTime_CheckedChanged);
            // 
            // lTimeRange
            // 
            resources.ApplyResources(this.lTimeRange, "lTimeRange");
            this.lTimeRange.Name = "lTimeRange";
            // 
            // lDistanceRange
            // 
            resources.ApplyResources(this.lDistanceRange, "lDistanceRange");
            this.lDistanceRange.Name = "lDistanceRange";
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            resources.ApplyResources(this.panel1, "panel1");
            this.panel1.Name = "panel1";
            // 
            // cbFinishCommands
            // 
            resources.ApplyResources(this.cbFinishCommands, "cbFinishCommands");
            this.cbFinishCommands.Name = "cbFinishCommands";
            this.cbFinishCommands.UseVisualStyleBackColor = true;
            this.cbFinishCommands.CheckedChanged += new System.EventHandler(this.CbFinishCommands_CheckedChanged);
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.rbForward);
            this.panel2.Controls.Add(this.rbBackward);
            resources.ApplyResources(this.panel2, "panel2");
            this.panel2.Name = "panel2";
            // 
            // StraightPanel
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.cbSpeed);
            this.Controls.Add(this.cbFinishCommands);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.lFlowchart);
            this.Controls.Add(this.rbContiniously);
            this.Controls.Add(this.rbDistance);
            this.Controls.Add(this.cbTime);
            this.Controls.Add(this.cbDistance);
            this.Controls.Add(this.nudTime);
            this.Controls.Add(this.nudDistance);
            this.Controls.Add(this.rbTime);
            this.Controls.Add(this.lTimeRange);
            this.Controls.Add(this.lDistanceRange);
            this.Controls.Add(this.nudSpeed);
            this.Controls.Add(this.lSpeedRange);
            this.Controls.Add(this.lSpeed);
            this.Controls.Add(this.lDirection);
            resources.ApplyResources(this, "$this");
            this.Name = "StraightPanel";
            this.Controls.SetChildIndex(this.lDirection, 0);
            this.Controls.SetChildIndex(this.lSpeed, 0);
            this.Controls.SetChildIndex(this.lActionName, 0);
            this.Controls.SetChildIndex(this.lSpeedRange, 0);
            this.Controls.SetChildIndex(this.nudSpeed, 0);
            this.Controls.SetChildIndex(this.lDistanceRange, 0);
            this.Controls.SetChildIndex(this.lTimeRange, 0);
            this.Controls.SetChildIndex(this.rbTime, 0);
            this.Controls.SetChildIndex(this.nudDistance, 0);
            this.Controls.SetChildIndex(this.nudTime, 0);
            this.Controls.SetChildIndex(this.cbDistance, 0);
            this.Controls.SetChildIndex(this.cbTime, 0);
            this.Controls.SetChildIndex(this.rbDistance, 0);
            this.Controls.SetChildIndex(this.rbContiniously, 0);
            this.Controls.SetChildIndex(this.lFlowchart, 0);
            this.Controls.SetChildIndex(this.panel1, 0);
            this.Controls.SetChildIndex(this.cbFinishCommands, 0);
            this.Controls.SetChildIndex(this.cbSpeed, 0);
            this.Controls.SetChildIndex(this.panel2, 0);
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label lSpeed;
        private Moway.Template.Controls.MowayRadioButton rbForward;
        private Moway.Template.Controls.MowayNumericUpDown nudSpeed;
        private System.Windows.Forms.Label lSpeedRange;
        private Moway.Template.Controls.MowayRadioButton rbBackward;
        private Moway.Template.Controls.MowayComboBox cbSpeed;
        private System.Windows.Forms.Label lDirection;
        private System.Windows.Forms.Label lFlowchart;
        private Moway.Template.Controls.MowayRadioButton rbContiniously;
        private Moway.Template.Controls.MowayRadioButton rbDistance;
        private Moway.Template.Controls.MowayComboBox cbTime;
        private Moway.Template.Controls.MowayComboBox cbDistance;
        private Moway.Template.Controls.MowayNumericUpDown nudTime;
        private Moway.Template.Controls.MowayNumericUpDown nudDistance;
        private Moway.Template.Controls.MowayRadioButton rbTime;
        private System.Windows.Forms.Label lTimeRange;
        private System.Windows.Forms.Label lDistanceRange;
        private System.Windows.Forms.Panel panel1;
        private Moway.Template.Controls.MowayCheckBox cbFinishCommands;
        private System.Windows.Forms.Panel panel2;
    }
}
