namespace Moway.Simulator
{
    partial class SimulatorPanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SimulatorPanel));
            this.bReset = new Moway.Template.Controls.MowayButton();
            this.bRun = new Moway.Template.Controls.MowayButton();
            this.bStepOver = new Moway.Template.Controls.MowayButton();
            this.bStepIn = new Moway.Template.Controls.MowayButton();
            this.cbMowayModule = new Moway.Template.Controls.MowayComboBox();
            this.separator1 = new System.Windows.Forms.Panel();
            this.bPause = new Moway.Template.Controls.MowayButton();
            this.separator2 = new System.Windows.Forms.Panel();
            this.toolTip = new Moway.Template.Controls.MowayToolTip();
            this.bAnimate = new Moway.Template.Controls.MowayButton();
            this.SuspendLayout();
            // 
            // bReset
            // 
            this.bReset.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            this.bReset.FlatAppearance.BorderSize = 0;
            this.bReset.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bReset.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.bReset.Image = ((System.Drawing.Image)(resources.GetObject("bReset.Image")));
            this.bReset.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.bReset.Location = new System.Drawing.Point(114, 8);
            this.bReset.Name = "bReset";
            this.bReset.Size = new System.Drawing.Size(19, 18);
            this.bReset.TabIndex = 55;
            this.bReset.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.toolTip.SetToolTip(this.bReset, "Reset");
            this.bReset.UseVisualStyleBackColor = true;
            this.bReset.Click += new System.EventHandler(this.BReset_Click);
            // 
            // bRun
            // 
            this.bRun.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.bRun.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            this.bRun.FlatAppearance.BorderSize = 0;
            this.bRun.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bRun.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.bRun.Image = ((System.Drawing.Image)(resources.GetObject("bRun.Image")));
            this.bRun.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.bRun.Location = new System.Drawing.Point(39, 8);
            this.bRun.Name = "bRun";
            this.bRun.Size = new System.Drawing.Size(19, 18);
            this.bRun.TabIndex = 54;
            this.bRun.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.toolTip.SetToolTip(this.bRun, "Run (F5)");
            this.bRun.UseVisualStyleBackColor = true;
            this.bRun.Click += new System.EventHandler(this.BRun_Click);
            // 
            // bStepOver
            // 
            this.bStepOver.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            this.bStepOver.FlatAppearance.BorderSize = 0;
            this.bStepOver.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bStepOver.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.bStepOver.Image = ((System.Drawing.Image)(resources.GetObject("bStepOver.Image")));
            this.bStepOver.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.bStepOver.Location = new System.Drawing.Point(171, 8);
            this.bStepOver.Name = "bStepOver";
            this.bStepOver.Size = new System.Drawing.Size(19, 18);
            this.bStepOver.TabIndex = 57;
            this.bStepOver.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.toolTip.SetToolTip(this.bStepOver, "Step Over (F11)");
            this.bStepOver.UseVisualStyleBackColor = true;
            this.bStepOver.Click += new System.EventHandler(this.BStepOver_Click);
            // 
            // bStepIn
            // 
            this.bStepIn.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            this.bStepIn.FlatAppearance.BorderSize = 0;
            this.bStepIn.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bStepIn.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.bStepIn.Image = ((System.Drawing.Image)(resources.GetObject("bStepIn.Image")));
            this.bStepIn.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.bStepIn.Location = new System.Drawing.Point(146, 8);
            this.bStepIn.Name = "bStepIn";
            this.bStepIn.Size = new System.Drawing.Size(19, 18);
            this.bStepIn.TabIndex = 58;
            this.bStepIn.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.toolTip.SetToolTip(this.bStepIn, "Step In (F10)");
            this.bStepIn.UseVisualStyleBackColor = true;
            this.bStepIn.Click += new System.EventHandler(this.BStepIn_Click);
            // 
            // cbMowayModule
            // 
            this.cbMowayModule.BackColor = System.Drawing.Color.White;
            this.cbMowayModule.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbMowayModule.DropDownHeight = 100;
            this.cbMowayModule.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbMowayModule.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbMowayModule.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cbMowayModule.FormattingEnabled = true;
            this.cbMowayModule.IntegralHeight = false;
            this.cbMowayModule.Location = new System.Drawing.Point(19, 47);
            this.cbMowayModule.Name = "cbMowayModule";
            this.cbMowayModule.Size = new System.Drawing.Size(190, 22);
            this.cbMowayModule.TabIndex = 62;
            this.cbMowayModule.SelectedIndexChanged += new System.EventHandler(this.CbMowayModel_SelectedIndexChanged);
            // 
            // separator1
            // 
            this.separator1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            this.separator1.Location = new System.Drawing.Point(139, 8);
            this.separator1.Name = "separator1";
            this.separator1.Size = new System.Drawing.Size(1, 19);
            this.separator1.TabIndex = 61;
            // 
            // bPause
            // 
            this.bPause.Enabled = false;
            this.bPause.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            this.bPause.FlatAppearance.BorderSize = 0;
            this.bPause.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bPause.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.bPause.Image = ((System.Drawing.Image)(resources.GetObject("bPause.Image")));
            this.bPause.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.bPause.Location = new System.Drawing.Point(89, 8);
            this.bPause.Name = "bPause";
            this.bPause.Size = new System.Drawing.Size(19, 18);
            this.bPause.TabIndex = 59;
            this.bPause.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.toolTip.SetToolTip(this.bPause, "Pause (Ctrl+F5)");
            this.bPause.UseVisualStyleBackColor = true;
            this.bPause.Click += new System.EventHandler(this.BPause_Click);
            // 
            // separator2
            // 
            this.separator2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            this.separator2.Location = new System.Drawing.Point(4, 35);
            this.separator2.Name = "separator2";
            this.separator2.Size = new System.Drawing.Size(220, 2);
            this.separator2.TabIndex = 63;
            // 
            // bAnimate
            // 
            this.bAnimate.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.bAnimate.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            this.bAnimate.FlatAppearance.BorderSize = 0;
            this.bAnimate.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bAnimate.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.bAnimate.Image = ((System.Drawing.Image)(resources.GetObject("bAnimate.Image")));
            this.bAnimate.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.bAnimate.Location = new System.Drawing.Point(64, 8);
            this.bAnimate.Name = "bAnimate";
            this.bAnimate.Size = new System.Drawing.Size(19, 18);
            this.bAnimate.TabIndex = 64;
            this.bAnimate.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.toolTip.SetToolTip(this.bAnimate, "Animate Simulation (F6)");
            this.bAnimate.UseVisualStyleBackColor = true;
            this.bAnimate.Click += new System.EventHandler(this.BAnimate_Click);
            // 
            // SimulatorPanel
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.bAnimate);
            this.Controls.Add(this.separator2);
            this.Controls.Add(this.cbMowayModule);
            this.Controls.Add(this.separator1);
            this.Controls.Add(this.bPause);
            this.Controls.Add(this.bStepIn);
            this.Controls.Add(this.bStepOver);
            this.Controls.Add(this.bReset);
            this.Controls.Add(this.bRun);
            this.Name = "SimulatorPanel";
            this.ResumeLayout(false);

        }

        #endregion

        private Moway.Template.Controls.MowayButton bReset;
        private Moway.Template.Controls.MowayButton bRun;
        private Moway.Template.Controls.MowayButton bStepOver;
        private Moway.Template.Controls.MowayButton bStepIn;
        private Moway.Template.Controls.MowayComboBox cbMowayModule;
        private System.Windows.Forms.Panel separator1;
        private Moway.Template.Controls.MowayButton bPause;
        private System.Windows.Forms.Panel separator2;
        private Moway.Template.Controls.MowayToolTip toolTip;
        private Moway.Template.Controls.MowayButton bAnimate;
    }
}
