namespace Moway.Simulator.Sensors
{
    partial class AccelerometerPanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AccelerometerPanel));
            this.lXAxis = new System.Windows.Forms.Label();
            this.lYAxis = new System.Windows.Forms.Label();
            this.lZAxis = new System.Windows.Forms.Label();
            this.pbAccelerationBackground = new System.Windows.Forms.PictureBox();
            this.lXAxisHelp = new System.Windows.Forms.Label();
            this.nudXAxis = new Moway.Template.Controls.MowayNumericUpDown();
            this.lYAxisHelp = new System.Windows.Forms.Label();
            this.nudYAxis = new Moway.Template.Controls.MowayNumericUpDown();
            this.lZAxisHelp = new System.Windows.Forms.Label();
            this.nudZAxis = new Moway.Template.Controls.MowayNumericUpDown();
            ((System.ComponentModel.ISupportInitialize)(this.pbAccelerationBackground)).BeginInit();
            this.SuspendLayout();
            // 
            // lXAxis
            // 
            this.lXAxis.AccessibleDescription = null;
            this.lXAxis.AccessibleName = null;
            resources.ApplyResources(this.lXAxis, "lXAxis");
            this.lXAxis.Name = "lXAxis";
            // 
            // lYAxis
            // 
            this.lYAxis.AccessibleDescription = null;
            this.lYAxis.AccessibleName = null;
            resources.ApplyResources(this.lYAxis, "lYAxis");
            this.lYAxis.Name = "lYAxis";
            // 
            // lZAxis
            // 
            this.lZAxis.AccessibleDescription = null;
            this.lZAxis.AccessibleName = null;
            resources.ApplyResources(this.lZAxis, "lZAxis");
            this.lZAxis.Name = "lZAxis";
            // 
            // pbAccelerationBackground
            // 
            this.pbAccelerationBackground.AccessibleDescription = null;
            this.pbAccelerationBackground.AccessibleName = null;
            resources.ApplyResources(this.pbAccelerationBackground, "pbAccelerationBackground");
            this.pbAccelerationBackground.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pbAccelerationBackground.Font = null;
            this.pbAccelerationBackground.ImageLocation = null;
            this.pbAccelerationBackground.Name = "pbAccelerationBackground";
            this.pbAccelerationBackground.TabStop = false;
            // 
            // lXAxisHelp
            // 
            this.lXAxisHelp.AccessibleDescription = null;
            this.lXAxisHelp.AccessibleName = null;
            resources.ApplyResources(this.lXAxisHelp, "lXAxisHelp");
            this.lXAxisHelp.Name = "lXAxisHelp";
            // 
            // nudXAxis
            // 
            this.nudXAxis.AccessibleDescription = null;
            this.nudXAxis.AccessibleName = null;
            resources.ApplyResources(this.nudXAxis, "nudXAxis");
            this.nudXAxis.BackColor = System.Drawing.Color.White;
            this.nudXAxis.BackgroundImage = null;
            this.nudXAxis.DecimalPlaces = 2;
            this.nudXAxis.Increment = new decimal(new int[] {
            5,
            0,
            0,
            131072});
            this.nudXAxis.Maximum = new decimal(new int[] {
            2,
            0,
            0,
            0});
            this.nudXAxis.Minimum = new decimal(new int[] {
            2,
            0,
            0,
            -2147483648});
            this.nudXAxis.Name = "nudXAxis";
            this.nudXAxis.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudXAxis.ValueChanged += new System.EventHandler(this.nudAxis_ValueChanged);
            // 
            // lYAxisHelp
            // 
            this.lYAxisHelp.AccessibleDescription = null;
            this.lYAxisHelp.AccessibleName = null;
            resources.ApplyResources(this.lYAxisHelp, "lYAxisHelp");
            this.lYAxisHelp.Name = "lYAxisHelp";
            // 
            // nudYAxis
            // 
            this.nudYAxis.AccessibleDescription = null;
            this.nudYAxis.AccessibleName = null;
            resources.ApplyResources(this.nudYAxis, "nudYAxis");
            this.nudYAxis.BackColor = System.Drawing.Color.White;
            this.nudYAxis.BackgroundImage = null;
            this.nudYAxis.DecimalPlaces = 2;
            this.nudYAxis.Increment = new decimal(new int[] {
            5,
            0,
            0,
            131072});
            this.nudYAxis.Maximum = new decimal(new int[] {
            2,
            0,
            0,
            0});
            this.nudYAxis.Minimum = new decimal(new int[] {
            2,
            0,
            0,
            -2147483648});
            this.nudYAxis.Name = "nudYAxis";
            this.nudYAxis.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudYAxis.ValueChanged += new System.EventHandler(this.nudAxis_ValueChanged);
            // 
            // lZAxisHelp
            // 
            this.lZAxisHelp.AccessibleDescription = null;
            this.lZAxisHelp.AccessibleName = null;
            resources.ApplyResources(this.lZAxisHelp, "lZAxisHelp");
            this.lZAxisHelp.Name = "lZAxisHelp";
            // 
            // nudZAxis
            // 
            this.nudZAxis.AccessibleDescription = null;
            this.nudZAxis.AccessibleName = null;
            resources.ApplyResources(this.nudZAxis, "nudZAxis");
            this.nudZAxis.BackColor = System.Drawing.Color.White;
            this.nudZAxis.BackgroundImage = null;
            this.nudZAxis.DecimalPlaces = 2;
            this.nudZAxis.Increment = new decimal(new int[] {
            5,
            0,
            0,
            131072});
            this.nudZAxis.Maximum = new decimal(new int[] {
            2,
            0,
            0,
            0});
            this.nudZAxis.Minimum = new decimal(new int[] {
            2,
            0,
            0,
            -2147483648});
            this.nudZAxis.Name = "nudZAxis";
            this.nudZAxis.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudZAxis.ValueChanged += new System.EventHandler(this.nudAxis_ValueChanged);
            // 
            // AccelerometerPanel
            // 
            this.AccessibleDescription = null;
            this.AccessibleName = null;
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = null;
            this.Controls.Add(this.lZAxisHelp);
            this.Controls.Add(this.nudZAxis);
            this.Controls.Add(this.lYAxisHelp);
            this.Controls.Add(this.nudYAxis);
            this.Controls.Add(this.lXAxisHelp);
            this.Controls.Add(this.nudXAxis);
            this.Controls.Add(this.lXAxis);
            this.Controls.Add(this.lYAxis);
            this.Controls.Add(this.lZAxis);
            this.Controls.Add(this.pbAccelerationBackground);
            this.Name = "AccelerometerPanel";
            ((System.ComponentModel.ISupportInitialize)(this.pbAccelerationBackground)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label lXAxis;
        private System.Windows.Forms.Label lYAxis;
        private System.Windows.Forms.Label lZAxis;
        private System.Windows.Forms.PictureBox pbAccelerationBackground;
        private System.Windows.Forms.Label lXAxisHelp;
        private Moway.Template.Controls.MowayNumericUpDown nudXAxis;
        private System.Windows.Forms.Label lYAxisHelp;
        private Moway.Template.Controls.MowayNumericUpDown nudYAxis;
        private System.Windows.Forms.Label lZAxisHelp;
        private Moway.Template.Controls.MowayNumericUpDown nudZAxis;
    }
}
