namespace Moway.Simulator.Sensors
{
    partial class EnviromentPanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(EnviromentPanel));
            this.pbEnvromentBackground = new System.Windows.Forms.PictureBox();
            this.lNoise = new System.Windows.Forms.Label();
            this.lTemperature = new System.Windows.Forms.Label();
            this.lBrightness = new System.Windows.Forms.Label();
            this.lTemperatureHelp = new System.Windows.Forms.Label();
            this.nudTemperature = new Moway.Template.Controls.MowayNumericUpDown();
            this.lBrightnessHelp = new System.Windows.Forms.Label();
            this.nudBrightness = new Moway.Template.Controls.MowayNumericUpDown();
            this.lNoiseHelp = new System.Windows.Forms.Label();
            this.nudNoise = new Moway.Template.Controls.MowayNumericUpDown();
            ((System.ComponentModel.ISupportInitialize)(this.pbEnvromentBackground)).BeginInit();
            this.SuspendLayout();
            // 
            // pbEnvromentBackground
            // 
            this.pbEnvromentBackground.AccessibleDescription = null;
            this.pbEnvromentBackground.AccessibleName = null;
            resources.ApplyResources(this.pbEnvromentBackground, "pbEnvromentBackground");
            this.pbEnvromentBackground.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pbEnvromentBackground.Font = null;
            this.pbEnvromentBackground.ImageLocation = null;
            this.pbEnvromentBackground.Name = "pbEnvromentBackground";
            this.pbEnvromentBackground.TabStop = false;
            // 
            // lNoise
            // 
            this.lNoise.AccessibleDescription = null;
            this.lNoise.AccessibleName = null;
            resources.ApplyResources(this.lNoise, "lNoise");
            this.lNoise.Name = "lNoise";
            // 
            // lTemperature
            // 
            this.lTemperature.AccessibleDescription = null;
            this.lTemperature.AccessibleName = null;
            resources.ApplyResources(this.lTemperature, "lTemperature");
            this.lTemperature.Name = "lTemperature";
            // 
            // lBrightness
            // 
            this.lBrightness.AccessibleDescription = null;
            this.lBrightness.AccessibleName = null;
            resources.ApplyResources(this.lBrightness, "lBrightness");
            this.lBrightness.Name = "lBrightness";
            // 
            // lTemperatureHelp
            // 
            this.lTemperatureHelp.AccessibleDescription = null;
            this.lTemperatureHelp.AccessibleName = null;
            resources.ApplyResources(this.lTemperatureHelp, "lTemperatureHelp");
            this.lTemperatureHelp.Name = "lTemperatureHelp";
            // 
            // nudTemperature
            // 
            this.nudTemperature.AccessibleDescription = null;
            this.nudTemperature.AccessibleName = null;
            resources.ApplyResources(this.nudTemperature, "nudTemperature");
            this.nudTemperature.BackColor = System.Drawing.Color.White;
            this.nudTemperature.BackgroundImage = null;
            this.nudTemperature.DecimalPlaces = 0;
            this.nudTemperature.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudTemperature.Maximum = new decimal(new int[] {
            255,
            0,
            0,
            0});
            this.nudTemperature.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudTemperature.Name = "nudTemperature";
            this.nudTemperature.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudTemperature.ValueChanged += new System.EventHandler(this.nudTemperature_ValueChanged);
            // 
            // lBrightnessHelp
            // 
            this.lBrightnessHelp.AccessibleDescription = null;
            this.lBrightnessHelp.AccessibleName = null;
            resources.ApplyResources(this.lBrightnessHelp, "lBrightnessHelp");
            this.lBrightnessHelp.Name = "lBrightnessHelp";
            // 
            // nudBrightness
            // 
            this.nudBrightness.AccessibleDescription = null;
            this.nudBrightness.AccessibleName = null;
            resources.ApplyResources(this.nudBrightness, "nudBrightness");
            this.nudBrightness.BackColor = System.Drawing.Color.White;
            this.nudBrightness.BackgroundImage = null;
            this.nudBrightness.DecimalPlaces = 0;
            this.nudBrightness.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudBrightness.Maximum = new decimal(new int[] {
            100,
            0,
            0,
            0});
            this.nudBrightness.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudBrightness.Name = "nudBrightness";
            this.nudBrightness.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudBrightness.ValueChanged += new System.EventHandler(this.nudBrightness_ValueChanged);
            // 
            // lNoiseHelp
            // 
            this.lNoiseHelp.AccessibleDescription = null;
            this.lNoiseHelp.AccessibleName = null;
            resources.ApplyResources(this.lNoiseHelp, "lNoiseHelp");
            this.lNoiseHelp.Name = "lNoiseHelp";
            // 
            // nudNoise
            // 
            this.nudNoise.AccessibleDescription = null;
            this.nudNoise.AccessibleName = null;
            resources.ApplyResources(this.nudNoise, "nudNoise");
            this.nudNoise.BackColor = System.Drawing.Color.White;
            this.nudNoise.BackgroundImage = null;
            this.nudNoise.DecimalPlaces = 0;
            this.nudNoise.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudNoise.Maximum = new decimal(new int[] {
            100,
            0,
            0,
            0});
            this.nudNoise.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudNoise.Name = "nudNoise";
            this.nudNoise.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudNoise.ValueChanged += new System.EventHandler(this.nudNoise_ValueChanged);
            // 
            // EnviromentPanel
            // 
            this.AccessibleDescription = null;
            this.AccessibleName = null;
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = null;
            this.Controls.Add(this.lNoiseHelp);
            this.Controls.Add(this.nudNoise);
            this.Controls.Add(this.lBrightnessHelp);
            this.Controls.Add(this.nudBrightness);
            this.Controls.Add(this.lTemperatureHelp);
            this.Controls.Add(this.nudTemperature);
            this.Controls.Add(this.lNoise);
            this.Controls.Add(this.lTemperature);
            this.Controls.Add(this.lBrightness);
            this.Controls.Add(this.pbEnvromentBackground);
            this.Name = "EnviromentPanel";
            ((System.ComponentModel.ISupportInitialize)(this.pbEnvromentBackground)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.PictureBox pbEnvromentBackground;
        private System.Windows.Forms.Label lNoise;
        private System.Windows.Forms.Label lTemperature;
        private System.Windows.Forms.Label lBrightness;
        private System.Windows.Forms.Label lTemperatureHelp;
        private Moway.Template.Controls.MowayNumericUpDown nudTemperature;
        private System.Windows.Forms.Label lBrightnessHelp;
        private Moway.Template.Controls.MowayNumericUpDown nudBrightness;
        private System.Windows.Forms.Label lNoiseHelp;
        private Moway.Template.Controls.MowayNumericUpDown nudNoise;
    }
}
