namespace Moway.Project.GraphicProject.Actions.TransmissionRf
{
    partial class TransmissionRfPanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(TransmissionRfPanel));
            this.nudDirection = new Moway.Template.Controls.MowayNumericUpDown();
            this.lData7 = new System.Windows.Forms.Label();
            this.nudValue7 = new Moway.Template.Controls.MowayNumericUpDown();
            this.cbVariable7 = new Moway.Template.Controls.MowayComboBox();
            this.lData6 = new System.Windows.Forms.Label();
            this.nudValue6 = new Moway.Template.Controls.MowayNumericUpDown();
            this.cbVariable6 = new Moway.Template.Controls.MowayComboBox();
            this.lData5 = new System.Windows.Forms.Label();
            this.nudValue5 = new Moway.Template.Controls.MowayNumericUpDown();
            this.cbVariable5 = new Moway.Template.Controls.MowayComboBox();
            this.lData4 = new System.Windows.Forms.Label();
            this.nudValue4 = new Moway.Template.Controls.MowayNumericUpDown();
            this.cbVariable4 = new Moway.Template.Controls.MowayComboBox();
            this.lData3 = new System.Windows.Forms.Label();
            this.lDirection = new System.Windows.Forms.Label();
            this.nudValue3 = new Moway.Template.Controls.MowayNumericUpDown();
            this.cbVariable3 = new Moway.Template.Controls.MowayComboBox();
            this.lData2 = new System.Windows.Forms.Label();
            this.nudValue2 = new Moway.Template.Controls.MowayNumericUpDown();
            this.cbVariable2 = new Moway.Template.Controls.MowayComboBox();
            this.lData0 = new System.Windows.Forms.Label();
            this.nudValue0 = new Moway.Template.Controls.MowayNumericUpDown();
            this.cbVariable0 = new Moway.Template.Controls.MowayComboBox();
            this.cbVariable1 = new Moway.Template.Controls.MowayComboBox();
            this.nudValue1 = new Moway.Template.Controls.MowayNumericUpDown();
            this.lData1 = new System.Windows.Forms.Label();
            this.lRange7 = new System.Windows.Forms.Label();
            this.lRange6 = new System.Windows.Forms.Label();
            this.lRange5 = new System.Windows.Forms.Label();
            this.lRange4 = new System.Windows.Forms.Label();
            this.lRange3 = new System.Windows.Forms.Label();
            this.lRange2 = new System.Windows.Forms.Label();
            this.lRange0 = new System.Windows.Forms.Label();
            this.lRange1 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // lActionName
            // 
            resources.ApplyResources(this.lActionName, "lActionName");
            // 
            // nudDirection
            // 
            this.nudDirection.BackColor = System.Drawing.Color.White;
            this.nudDirection.DecimalPlaces = 0;
            resources.ApplyResources(this.nudDirection, "nudDirection");
            this.nudDirection.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudDirection.Maximum = new decimal(new int[] {
            255,
            0,
            0,
            0});
            this.nudDirection.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudDirection.Name = "nudDirection";
            this.nudDirection.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudDirection.ValueChanged += new System.EventHandler(this.NudValue_ValueChanged);
            // 
            // lData7
            // 
            resources.ApplyResources(this.lData7, "lData7");
            this.lData7.Name = "lData7";
            // 
            // nudValue7
            // 
            this.nudValue7.BackColor = System.Drawing.Color.White;
            this.nudValue7.DecimalPlaces = 0;
            resources.ApplyResources(this.nudValue7, "nudValue7");
            this.nudValue7.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudValue7.Maximum = new decimal(new int[] {
            255,
            0,
            0,
            0});
            this.nudValue7.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudValue7.Name = "nudValue7";
            this.nudValue7.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudValue7.ValueChanged += new System.EventHandler(this.NudValue_ValueChanged);
            // 
            // cbVariable7
            // 
            this.cbVariable7.BackColor = System.Drawing.Color.White;
            this.cbVariable7.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbVariable7.DropDownHeight = 100;
            this.cbVariable7.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbVariable7, "cbVariable7");
            this.cbVariable7.FormattingEnabled = true;
            this.cbVariable7.Items.AddRange(new object[] {
            resources.GetString("cbVariable7.Items")});
            this.cbVariable7.Name = "cbVariable7";
            this.cbVariable7.SelectedIndexChanged += new System.EventHandler(this.CbVariable7_SelectedIndexChanged);
            // 
            // lData6
            // 
            resources.ApplyResources(this.lData6, "lData6");
            this.lData6.Name = "lData6";
            // 
            // nudValue6
            // 
            this.nudValue6.BackColor = System.Drawing.Color.White;
            this.nudValue6.DecimalPlaces = 0;
            resources.ApplyResources(this.nudValue6, "nudValue6");
            this.nudValue6.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudValue6.Maximum = new decimal(new int[] {
            255,
            0,
            0,
            0});
            this.nudValue6.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudValue6.Name = "nudValue6";
            this.nudValue6.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudValue6.ValueChanged += new System.EventHandler(this.NudValue_ValueChanged);
            // 
            // cbVariable6
            // 
            this.cbVariable6.BackColor = System.Drawing.Color.White;
            this.cbVariable6.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbVariable6.DropDownHeight = 100;
            this.cbVariable6.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbVariable6, "cbVariable6");
            this.cbVariable6.FormattingEnabled = true;
            this.cbVariable6.Items.AddRange(new object[] {
            resources.GetString("cbVariable6.Items")});
            this.cbVariable6.Name = "cbVariable6";
            this.cbVariable6.SelectedIndexChanged += new System.EventHandler(this.CbVariable6_SelectedIndexChanged);
            // 
            // lData5
            // 
            resources.ApplyResources(this.lData5, "lData5");
            this.lData5.Name = "lData5";
            // 
            // nudValue5
            // 
            this.nudValue5.BackColor = System.Drawing.Color.White;
            this.nudValue5.DecimalPlaces = 0;
            resources.ApplyResources(this.nudValue5, "nudValue5");
            this.nudValue5.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudValue5.Maximum = new decimal(new int[] {
            255,
            0,
            0,
            0});
            this.nudValue5.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudValue5.Name = "nudValue5";
            this.nudValue5.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudValue5.ValueChanged += new System.EventHandler(this.NudValue_ValueChanged);
            // 
            // cbVariable5
            // 
            this.cbVariable5.BackColor = System.Drawing.Color.White;
            this.cbVariable5.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbVariable5.DropDownHeight = 100;
            this.cbVariable5.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbVariable5, "cbVariable5");
            this.cbVariable5.FormattingEnabled = true;
            this.cbVariable5.Items.AddRange(new object[] {
            resources.GetString("cbVariable5.Items")});
            this.cbVariable5.Name = "cbVariable5";
            this.cbVariable5.SelectedIndexChanged += new System.EventHandler(this.CbVariable5_SelectedIndexChanged);
            // 
            // lData4
            // 
            resources.ApplyResources(this.lData4, "lData4");
            this.lData4.Name = "lData4";
            // 
            // nudValue4
            // 
            this.nudValue4.BackColor = System.Drawing.Color.White;
            this.nudValue4.DecimalPlaces = 0;
            resources.ApplyResources(this.nudValue4, "nudValue4");
            this.nudValue4.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudValue4.Maximum = new decimal(new int[] {
            255,
            0,
            0,
            0});
            this.nudValue4.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudValue4.Name = "nudValue4";
            this.nudValue4.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudValue4.ValueChanged += new System.EventHandler(this.NudValue_ValueChanged);
            // 
            // cbVariable4
            // 
            this.cbVariable4.BackColor = System.Drawing.Color.White;
            this.cbVariable4.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbVariable4.DropDownHeight = 100;
            this.cbVariable4.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbVariable4, "cbVariable4");
            this.cbVariable4.FormattingEnabled = true;
            this.cbVariable4.Items.AddRange(new object[] {
            resources.GetString("cbVariable4.Items")});
            this.cbVariable4.Name = "cbVariable4";
            this.cbVariable4.SelectedIndexChanged += new System.EventHandler(this.CbVariable4_SelectedIndexChanged);
            // 
            // lData3
            // 
            resources.ApplyResources(this.lData3, "lData3");
            this.lData3.Name = "lData3";
            // 
            // lDirection
            // 
            resources.ApplyResources(this.lDirection, "lDirection");
            this.lDirection.Name = "lDirection";
            // 
            // nudValue3
            // 
            this.nudValue3.BackColor = System.Drawing.Color.White;
            this.nudValue3.DecimalPlaces = 0;
            resources.ApplyResources(this.nudValue3, "nudValue3");
            this.nudValue3.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudValue3.Maximum = new decimal(new int[] {
            255,
            0,
            0,
            0});
            this.nudValue3.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudValue3.Name = "nudValue3";
            this.nudValue3.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudValue3.ValueChanged += new System.EventHandler(this.NudValue_ValueChanged);
            // 
            // cbVariable3
            // 
            this.cbVariable3.BackColor = System.Drawing.Color.White;
            this.cbVariable3.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbVariable3.DropDownHeight = 100;
            this.cbVariable3.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbVariable3, "cbVariable3");
            this.cbVariable3.FormattingEnabled = true;
            this.cbVariable3.Items.AddRange(new object[] {
            resources.GetString("cbVariable3.Items")});
            this.cbVariable3.Name = "cbVariable3";
            this.cbVariable3.SelectedIndexChanged += new System.EventHandler(this.CbVariable3_SelectedIndexChanged);
            // 
            // lData2
            // 
            resources.ApplyResources(this.lData2, "lData2");
            this.lData2.Name = "lData2";
            // 
            // nudValue2
            // 
            this.nudValue2.BackColor = System.Drawing.Color.White;
            this.nudValue2.DecimalPlaces = 0;
            resources.ApplyResources(this.nudValue2, "nudValue2");
            this.nudValue2.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudValue2.Maximum = new decimal(new int[] {
            255,
            0,
            0,
            0});
            this.nudValue2.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudValue2.Name = "nudValue2";
            this.nudValue2.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudValue2.ValueChanged += new System.EventHandler(this.NudValue_ValueChanged);
            // 
            // cbVariable2
            // 
            this.cbVariable2.BackColor = System.Drawing.Color.White;
            this.cbVariable2.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbVariable2.DropDownHeight = 100;
            this.cbVariable2.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbVariable2, "cbVariable2");
            this.cbVariable2.FormattingEnabled = true;
            this.cbVariable2.Items.AddRange(new object[] {
            resources.GetString("cbVariable2.Items")});
            this.cbVariable2.Name = "cbVariable2";
            this.cbVariable2.SelectedIndexChanged += new System.EventHandler(this.CbVariable2_SelectedIndexChanged);
            // 
            // lData0
            // 
            resources.ApplyResources(this.lData0, "lData0");
            this.lData0.Name = "lData0";
            // 
            // nudValue0
            // 
            this.nudValue0.BackColor = System.Drawing.Color.White;
            this.nudValue0.DecimalPlaces = 0;
            resources.ApplyResources(this.nudValue0, "nudValue0");
            this.nudValue0.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudValue0.Maximum = new decimal(new int[] {
            255,
            0,
            0,
            0});
            this.nudValue0.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudValue0.Name = "nudValue0";
            this.nudValue0.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudValue0.ValueChanged += new System.EventHandler(this.NudValue_ValueChanged);
            // 
            // cbVariable0
            // 
            this.cbVariable0.BackColor = System.Drawing.Color.White;
            this.cbVariable0.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbVariable0.DropDownHeight = 100;
            this.cbVariable0.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbVariable0, "cbVariable0");
            this.cbVariable0.FormattingEnabled = true;
            this.cbVariable0.Items.AddRange(new object[] {
            resources.GetString("cbVariable0.Items")});
            this.cbVariable0.Name = "cbVariable0";
            this.cbVariable0.SelectedIndexChanged += new System.EventHandler(this.CbVariable0_SelectedIndexChanged);
            // 
            // cbVariable1
            // 
            this.cbVariable1.BackColor = System.Drawing.Color.White;
            this.cbVariable1.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbVariable1.DropDownHeight = 100;
            this.cbVariable1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbVariable1, "cbVariable1");
            this.cbVariable1.FormattingEnabled = true;
            this.cbVariable1.Items.AddRange(new object[] {
            resources.GetString("cbVariable1.Items")});
            this.cbVariable1.Name = "cbVariable1";
            this.cbVariable1.SelectedIndexChanged += new System.EventHandler(this.CbVariable1_SelectedIndexChanged);
            // 
            // nudValue1
            // 
            this.nudValue1.BackColor = System.Drawing.Color.White;
            this.nudValue1.DecimalPlaces = 0;
            resources.ApplyResources(this.nudValue1, "nudValue1");
            this.nudValue1.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudValue1.Maximum = new decimal(new int[] {
            255,
            0,
            0,
            0});
            this.nudValue1.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudValue1.Name = "nudValue1";
            this.nudValue1.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudValue1.ValueChanged += new System.EventHandler(this.NudValue_ValueChanged);
            // 
            // lData1
            // 
            resources.ApplyResources(this.lData1, "lData1");
            this.lData1.Name = "lData1";
            // 
            // lRange7
            // 
            resources.ApplyResources(this.lRange7, "lRange7");
            this.lRange7.Name = "lRange7";
            // 
            // lRange6
            // 
            resources.ApplyResources(this.lRange6, "lRange6");
            this.lRange6.Name = "lRange6";
            // 
            // lRange5
            // 
            resources.ApplyResources(this.lRange5, "lRange5");
            this.lRange5.Name = "lRange5";
            // 
            // lRange4
            // 
            resources.ApplyResources(this.lRange4, "lRange4");
            this.lRange4.Name = "lRange4";
            // 
            // lRange3
            // 
            resources.ApplyResources(this.lRange3, "lRange3");
            this.lRange3.Name = "lRange3";
            // 
            // lRange2
            // 
            resources.ApplyResources(this.lRange2, "lRange2");
            this.lRange2.Name = "lRange2";
            // 
            // lRange0
            // 
            resources.ApplyResources(this.lRange0, "lRange0");
            this.lRange0.Name = "lRange0";
            // 
            // lRange1
            // 
            resources.ApplyResources(this.lRange1, "lRange1");
            this.lRange1.Name = "lRange1";
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // TransmissionRfPanel
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.label1);
            this.Controls.Add(this.lRange7);
            this.Controls.Add(this.lRange6);
            this.Controls.Add(this.lRange5);
            this.Controls.Add(this.lRange4);
            this.Controls.Add(this.lRange3);
            this.Controls.Add(this.lRange2);
            this.Controls.Add(this.lRange0);
            this.Controls.Add(this.lRange1);
            this.Controls.Add(this.nudDirection);
            this.Controls.Add(this.nudValue7);
            this.Controls.Add(this.cbVariable7);
            this.Controls.Add(this.nudValue6);
            this.Controls.Add(this.cbVariable6);
            this.Controls.Add(this.nudValue5);
            this.Controls.Add(this.cbVariable5);
            this.Controls.Add(this.nudValue4);
            this.Controls.Add(this.cbVariable4);
            this.Controls.Add(this.nudValue3);
            this.Controls.Add(this.cbVariable3);
            this.Controls.Add(this.nudValue2);
            this.Controls.Add(this.cbVariable2);
            this.Controls.Add(this.nudValue0);
            this.Controls.Add(this.cbVariable0);
            this.Controls.Add(this.cbVariable1);
            this.Controls.Add(this.nudValue1);
            this.Controls.Add(this.lData7);
            this.Controls.Add(this.lData6);
            this.Controls.Add(this.lData5);
            this.Controls.Add(this.lData4);
            this.Controls.Add(this.lData3);
            this.Controls.Add(this.lDirection);
            this.Controls.Add(this.lData2);
            this.Controls.Add(this.lData0);
            this.Controls.Add(this.lData1);
            resources.ApplyResources(this, "$this");
            this.Name = "TransmissionRfPanel";
            this.Controls.SetChildIndex(this.lData1, 0);
            this.Controls.SetChildIndex(this.lData0, 0);
            this.Controls.SetChildIndex(this.lData2, 0);
            this.Controls.SetChildIndex(this.lDirection, 0);
            this.Controls.SetChildIndex(this.lData3, 0);
            this.Controls.SetChildIndex(this.lData4, 0);
            this.Controls.SetChildIndex(this.lData5, 0);
            this.Controls.SetChildIndex(this.lData6, 0);
            this.Controls.SetChildIndex(this.lData7, 0);
            this.Controls.SetChildIndex(this.lActionName, 0);
            this.Controls.SetChildIndex(this.nudValue1, 0);
            this.Controls.SetChildIndex(this.cbVariable1, 0);
            this.Controls.SetChildIndex(this.cbVariable0, 0);
            this.Controls.SetChildIndex(this.nudValue0, 0);
            this.Controls.SetChildIndex(this.cbVariable2, 0);
            this.Controls.SetChildIndex(this.nudValue2, 0);
            this.Controls.SetChildIndex(this.cbVariable3, 0);
            this.Controls.SetChildIndex(this.nudValue3, 0);
            this.Controls.SetChildIndex(this.cbVariable4, 0);
            this.Controls.SetChildIndex(this.nudValue4, 0);
            this.Controls.SetChildIndex(this.cbVariable5, 0);
            this.Controls.SetChildIndex(this.nudValue5, 0);
            this.Controls.SetChildIndex(this.cbVariable6, 0);
            this.Controls.SetChildIndex(this.nudValue6, 0);
            this.Controls.SetChildIndex(this.cbVariable7, 0);
            this.Controls.SetChildIndex(this.nudValue7, 0);
            this.Controls.SetChildIndex(this.nudDirection, 0);
            this.Controls.SetChildIndex(this.lRange1, 0);
            this.Controls.SetChildIndex(this.lRange0, 0);
            this.Controls.SetChildIndex(this.lRange2, 0);
            this.Controls.SetChildIndex(this.lRange3, 0);
            this.Controls.SetChildIndex(this.lRange4, 0);
            this.Controls.SetChildIndex(this.lRange5, 0);
            this.Controls.SetChildIndex(this.lRange6, 0);
            this.Controls.SetChildIndex(this.lRange7, 0);
            this.Controls.SetChildIndex(this.label1, 0);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Moway.Template.Controls.MowayNumericUpDown nudDirection;
        private System.Windows.Forms.Label lData7;
        private Moway.Template.Controls.MowayNumericUpDown nudValue7;
        private Moway.Template.Controls.MowayComboBox cbVariable7;
        private System.Windows.Forms.Label lData6;
        private Moway.Template.Controls.MowayNumericUpDown nudValue6;
        private Moway.Template.Controls.MowayComboBox cbVariable6;
        private System.Windows.Forms.Label lData5;
        private Moway.Template.Controls.MowayNumericUpDown nudValue5;
        private Moway.Template.Controls.MowayComboBox cbVariable5;
        private System.Windows.Forms.Label lData4;
        private Moway.Template.Controls.MowayNumericUpDown nudValue4;
        private Moway.Template.Controls.MowayComboBox cbVariable4;
        private System.Windows.Forms.Label lData3;
        private System.Windows.Forms.Label lDirection;
        private Moway.Template.Controls.MowayNumericUpDown nudValue3;
        private Moway.Template.Controls.MowayComboBox cbVariable3;
        private System.Windows.Forms.Label lData2;
        private Moway.Template.Controls.MowayNumericUpDown nudValue2;
        private Moway.Template.Controls.MowayComboBox cbVariable2;
        private System.Windows.Forms.Label lData0;
        private Moway.Template.Controls.MowayNumericUpDown nudValue0;
        private Moway.Template.Controls.MowayComboBox cbVariable0;
        private Moway.Template.Controls.MowayComboBox cbVariable1;
        private Moway.Template.Controls.MowayNumericUpDown nudValue1;
        private System.Windows.Forms.Label lData1;
        private System.Windows.Forms.Label lRange7;
        private System.Windows.Forms.Label lRange6;
        private System.Windows.Forms.Label lRange5;
        private System.Windows.Forms.Label lRange4;
        private System.Windows.Forms.Label lRange3;
        private System.Windows.Forms.Label lRange2;
        private System.Windows.Forms.Label lRange0;
        private System.Windows.Forms.Label lRange1;
        private System.Windows.Forms.Label label1;
    }
}
