//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//
//     Changes in this file may cause incorrect behavior and will be lost if
//     the code is rebuilt.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moway.Project.GraphicProject {
    using System;
    
    
    /// <summary>
    ///  Strongly typed resource class, to search for translated strings, etc.
    /// </summary>
    // StronglyTypedResourceBuilder automatically generated this class
    //  through a tool such as ResGen or Visual Studio.
    // To add or remove a member, edit the .ResX file and then run ResGen again
    // with the / str option or recompile your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GraphMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GraphMessages() {
        }
        
        /// <summary>
        ///  Returns the ResourceManager instance cached used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moway.Project.GraphicProject.GraphMessages", typeof(GraphMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Replaces the CurrentUICulture property of the current thread
        ///   for all resource searches using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Activate.
        /// </summary>
        internal static string ACTIVATE {
            get {
                return ResourceManager.GetString("ACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Animate.
        /// </summary>
        internal static string ANIMATE {
            get {
                return ResourceManager.GetString("ANIMATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Change Work Area Size.
        /// </summary>
        internal static string CHANGE_AREA_SIZE {
            get {
                return ResourceManager.GetString("CHANGE_AREA_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Check Diagrams.
        /// </summary>
        internal static string CHECK_DIAGRAMS {
            get {
                return ResourceManager.GetString("CHECK_DIAGRAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Compile.
        /// </summary>
        internal static string COMPILE_MOWAY {
            get {
                return ResourceManager.GetString("COMPILE_MOWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Connector tool.
        /// </summary>
        internal static string CONNECT_TOOL {
            get {
                return ResourceManager.GetString("CONNECT_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Are you sure you want to delete the function?.
        /// </summary>
        internal static string CONTINUE_DELETE {
            get {
                return ResourceManager.GetString("CONTINUE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Cursor tool.
        /// </summary>
        internal static string CURSOR_TOOL {
            get {
                return ResourceManager.GetString("CURSOR_TOOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Delete Function.
        /// </summary>
        internal static string DELETE_FUNCTION {
            get {
                return ResourceManager.GetString("DELETE_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to If you remove the selected function, you will lose the flowchart..
        /// </summary>
        internal static string DELETEFUNCTION_WARNING {
            get {
                return ResourceManager.GetString("DELETEFUNCTION_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Deactivate.
        /// </summary>
        internal static string DESACTIVATE {
            get {
                return ResourceManager.GetString("DESACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Edit Function.
        /// </summary>
        internal static string EDIT_FUNCTION {
            get {
                return ResourceManager.GetString("EDIT_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Export.
        /// </summary>
        internal static string EXPORT {
            get {
                return ResourceManager.GetString("EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to JPG Image.
        /// </summary>
        internal static string EXPORT_JPG {
            get {
                return ResourceManager.GetString("EXPORT_JPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to JPG Image (.jpg)|*.jpg.
        /// </summary>
        internal static string EXPORT_JPG_FILTER {
            get {
                return ResourceManager.GetString("EXPORT_JPG_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to PFD document.
        /// </summary>
        internal static string EXPORT_PDF {
            get {
                return ResourceManager.GetString("EXPORT_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to PDF Document (.pdf)|*.pdf.
        /// </summary>
        internal static string EXPORT_PDF_FILTER {
            get {
                return ResourceManager.GetString("EXPORT_PDF_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to PNG Image.
        /// </summary>
        internal static string EXPORT_PNG {
            get {
                return ResourceManager.GetString("EXPORT_PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to PNG Image (.png)|*.png.
        /// </summary>
        internal static string EXPORT_PNG_FILTER {
            get {
                return ResourceManager.GetString("EXPORT_PNG_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to The function selected is used in the diagram. Yo can not delete it..
        /// </summary>
        internal static string FUNCTION_IN_USE {
            get {
                return ResourceManager.GetString("FUNCTION_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Functions.
        /// </summary>
        internal static string FUNCTIONS {
            get {
                return ResourceManager.GetString("FUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to mOwayWorld Diagram (.mdg)|*.mdg.
        /// </summary>
        internal static string IMPORT_FILTER {
            get {
                return ResourceManager.GetString("IMPORT_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Import Function.
        /// </summary>
        internal static string IMPORT_FUNCTION {
            get {
                return ResourceManager.GetString("IMPORT_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Insert note.
        /// </summary>
        internal static string INSERT_NOTE {
            get {
                return ResourceManager.GetString("INSERT_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Main.
        /// </summary>
        internal static string MAIN {
            get {
                return ResourceManager.GetString("MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to New Function.
        /// </summary>
        internal static string NEW_FUNCTION {
            get {
                return ResourceManager.GetString("NEW_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to New Variable.
        /// </summary>
        internal static string NEW_VARIABLE {
            get {
                return ResourceManager.GetString("NEW_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Pause Simulation.
        /// </summary>
        internal static string PAUSE {
            get {
                return ResourceManager.GetString("PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Program mOway.
        /// </summary>
        internal static string PROGRAM_MOWAY {
            get {
                return ResourceManager.GetString("PROGRAM_MOWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Project.
        /// </summary>
        internal static string PROJECT {
            get {
                return ResourceManager.GetString("PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Properties.
        /// </summary>
        internal static string PROPERTIES {
            get {
                return ResourceManager.GetString("PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Reset Simulation.
        /// </summary>
        internal static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Run Simulation.
        /// </summary>
        internal static string RUN {
            get {
                return ResourceManager.GetString("RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Simulation.
        /// </summary>
        internal static string SIMULATION {
            get {
                return ResourceManager.GetString("SIMULATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to The simulation is complete..
        /// </summary>
        internal static string SIMULATION_FINISHED {
            get {
                return ResourceManager.GetString("SIMULATION_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Step In.
        /// </summary>
        internal static string STEP_IN {
            get {
                return ResourceManager.GetString("STEP_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Step Over.
        /// </summary>
        internal static string STEP_OVER {
            get {
                return ResourceManager.GetString("STEP_OVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Variables.
        /// </summary>
        internal static string VARIABLES {
            get {
                return ResourceManager.GetString("VARIABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to View Code.
        /// </summary>
        internal static string VIEW_CODE {
            get {
                return ResourceManager.GetString("VIEW_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Properties.
        /// </summary>
        internal static string VIEW_PROPERTIES {
            get {
                return ResourceManager.GetString("VIEW_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Results Window.
        /// </summary>
        internal static string VIEW_RESULTS {
            get {
                return ResourceManager.GetString("VIEW_RESULTS", resourceCulture);
            }
        }
    }
}
