namespace Moway.Project.GraphicProject.Actions.Rotate
{
    partial class RotatePanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(RotatePanel));
            this.lSpeed = new System.Windows.Forms.Label();
            this.rbRotateCenter = new Moway.Template.Controls.MowayRadioButton();
            this.nudSpeed = new Moway.Template.Controls.MowayNumericUpDown();
            this.lSpeedRange = new System.Windows.Forms.Label();
            this.rbRotateWheel = new Moway.Template.Controls.MowayRadioButton();
            this.cbSpeed = new Moway.Template.Controls.MowayComboBox();
            this.lRotation = new System.Windows.Forms.Label();
            this.cbRotateCenter = new Moway.Template.Controls.MowayComboBox();
            this.cbRotateWheel = new Moway.Template.Controls.MowayComboBox();
            this.cbFinishCommands = new Moway.Template.Controls.MowayCheckBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.lFlowchart = new System.Windows.Forms.Label();
            this.rbContiniously = new Moway.Template.Controls.MowayRadioButton();
            this.cbTime = new Moway.Template.Controls.MowayComboBox();
            this.nudTime = new Moway.Template.Controls.MowayNumericUpDown();
            this.rbTime = new Moway.Template.Controls.MowayRadioButton();
            this.lTimeRange = new System.Windows.Forms.Label();
            this.rbAngle = new Moway.Template.Controls.MowayRadioButton();
            this.cbAngle = new Moway.Template.Controls.MowayComboBox();
            this.nudAngle = new Moway.Template.Controls.MowayNumericUpDown();
            this.lAngleRange = new System.Windows.Forms.Label();
            this.panel2 = new System.Windows.Forms.Panel();
            this.panel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // lActionName
            // 
            resources.ApplyResources(this.lActionName, "lActionName");
            // 
            // lSpeed
            // 
            resources.ApplyResources(this.lSpeed, "lSpeed");
            this.lSpeed.Name = "lSpeed";
            // 
            // rbRotateCenter
            // 
            resources.ApplyResources(this.rbRotateCenter, "rbRotateCenter");
            this.rbRotateCenter.Checked = true;
            this.rbRotateCenter.Name = "rbRotateCenter";
            this.rbRotateCenter.TabStop = true;
            this.rbRotateCenter.UseVisualStyleBackColor = true;
            this.rbRotateCenter.CheckedChanged += new System.EventHandler(this.RbRotateCenter_CheckedChanged);
            // 
            // nudSpeed
            // 
            this.nudSpeed.BackColor = System.Drawing.Color.White;
            this.nudSpeed.DecimalPlaces = 0;
            resources.ApplyResources(this.nudSpeed, "nudSpeed");
            this.nudSpeed.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudSpeed.Maximum = new decimal(new int[] {
            100,
            0,
            0,
            0});
            this.nudSpeed.Minimum = new decimal(new int[] {
            30,
            0,
            0,
            0});
            this.nudSpeed.Name = "nudSpeed";
            this.nudSpeed.Value = new decimal(new int[] {
            30,
            0,
            0,
            0});
            this.nudSpeed.ValueChanged += new System.EventHandler(this.NudValue_ValueChanged);
            // 
            // lSpeedRange
            // 
            resources.ApplyResources(this.lSpeedRange, "lSpeedRange");
            this.lSpeedRange.Name = "lSpeedRange";
            // 
            // rbRotateWheel
            // 
            resources.ApplyResources(this.rbRotateWheel, "rbRotateWheel");
            this.rbRotateWheel.Name = "rbRotateWheel";
            this.rbRotateWheel.UseVisualStyleBackColor = true;
            // 
            // cbSpeed
            // 
            this.cbSpeed.BackColor = System.Drawing.Color.White;
            this.cbSpeed.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbSpeed.DropDownHeight = 100;
            this.cbSpeed.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbSpeed, "cbSpeed");
            this.cbSpeed.FormattingEnabled = true;
            this.cbSpeed.Items.AddRange(new object[] {
            resources.GetString("cbSpeed.Items")});
            this.cbSpeed.Name = "cbSpeed";
            this.cbSpeed.SelectedIndexChanged += new System.EventHandler(this.CbSpeed_SelectedIndexChanged);
            // 
            // lRotation
            // 
            resources.ApplyResources(this.lRotation, "lRotation");
            this.lRotation.Name = "lRotation";
            // 
            // cbRotateCenter
            // 
            this.cbRotateCenter.BackColor = System.Drawing.Color.White;
            this.cbRotateCenter.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbRotateCenter.DropDownHeight = 100;
            this.cbRotateCenter.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbRotateCenter, "cbRotateCenter");
            this.cbRotateCenter.FormattingEnabled = true;
            this.cbRotateCenter.Items.AddRange(new object[] {
            resources.GetString("cbRotateCenter.Items"),
            resources.GetString("cbRotateCenter.Items1")});
            this.cbRotateCenter.Name = "cbRotateCenter";
            this.cbRotateCenter.SelectedIndexChanged += new System.EventHandler(this.CbRotateMode_SelectedIndexChanged);
            // 
            // cbRotateWheel
            // 
            this.cbRotateWheel.BackColor = System.Drawing.Color.White;
            this.cbRotateWheel.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbRotateWheel.DropDownHeight = 100;
            this.cbRotateWheel.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbRotateWheel, "cbRotateWheel");
            this.cbRotateWheel.FormattingEnabled = true;
            this.cbRotateWheel.Items.AddRange(new object[] {
            resources.GetString("cbRotateWheel.Items"),
            resources.GetString("cbRotateWheel.Items1"),
            resources.GetString("cbRotateWheel.Items2"),
            resources.GetString("cbRotateWheel.Items3")});
            this.cbRotateWheel.Name = "cbRotateWheel";
            this.cbRotateWheel.SelectedIndexChanged += new System.EventHandler(this.CbRotateMode_SelectedIndexChanged);
            // 
            // cbFinishCommands
            // 
            resources.ApplyResources(this.cbFinishCommands, "cbFinishCommands");
            this.cbFinishCommands.Name = "cbFinishCommands";
            this.cbFinishCommands.UseVisualStyleBackColor = true;
            this.cbFinishCommands.CheckedChanged += new System.EventHandler(this.CbFinishCommands_CheckedChanged);
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            resources.ApplyResources(this.panel1, "panel1");
            this.panel1.Name = "panel1";
            // 
            // lFlowchart
            // 
            resources.ApplyResources(this.lFlowchart, "lFlowchart");
            this.lFlowchart.Name = "lFlowchart";
            // 
            // rbContiniously
            // 
            resources.ApplyResources(this.rbContiniously, "rbContiniously");
            this.rbContiniously.Checked = true;
            this.rbContiniously.Name = "rbContiniously";
            this.rbContiniously.TabStop = true;
            this.rbContiniously.UseVisualStyleBackColor = true;
            this.rbContiniously.CheckedChanged += new System.EventHandler(this.RbContiniously_CheckedChanged);
            // 
            // cbTime
            // 
            this.cbTime.BackColor = System.Drawing.Color.White;
            this.cbTime.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbTime.DropDownHeight = 100;
            this.cbTime.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbTime, "cbTime");
            this.cbTime.FormattingEnabled = true;
            this.cbTime.Items.AddRange(new object[] {
            resources.GetString("cbTime.Items")});
            this.cbTime.Name = "cbTime";
            this.cbTime.SelectedIndexChanged += new System.EventHandler(this.CbTime_SelectedIndexChanged);
            // 
            // nudTime
            // 
            this.nudTime.BackColor = System.Drawing.Color.White;
            this.nudTime.DecimalPlaces = 1;
            resources.ApplyResources(this.nudTime, "nudTime");
            this.nudTime.Increment = new decimal(new int[] {
            1,
            0,
            0,
            65536});
            this.nudTime.Maximum = new decimal(new int[] {
            255,
            0,
            0,
            65536});
            this.nudTime.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            65536});
            this.nudTime.Name = "nudTime";
            this.nudTime.Value = new decimal(new int[] {
            1,
            0,
            0,
            65536});
            this.nudTime.ValueChanged += new System.EventHandler(this.NudValue_ValueChanged);
            // 
            // rbTime
            // 
            resources.ApplyResources(this.rbTime, "rbTime");
            this.rbTime.Name = "rbTime";
            this.rbTime.UseVisualStyleBackColor = true;
            this.rbTime.CheckedChanged += new System.EventHandler(this.RbTime_CheckedChanged);
            // 
            // lTimeRange
            // 
            resources.ApplyResources(this.lTimeRange, "lTimeRange");
            this.lTimeRange.Name = "lTimeRange";
            // 
            // rbAngle
            // 
            resources.ApplyResources(this.rbAngle, "rbAngle");
            this.rbAngle.Name = "rbAngle";
            this.rbAngle.UseVisualStyleBackColor = true;
            this.rbAngle.CheckedChanged += new System.EventHandler(this.RbAngle_CheckedChanged);
            // 
            // cbAngle
            // 
            this.cbAngle.BackColor = System.Drawing.Color.White;
            this.cbAngle.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbAngle.DropDownHeight = 100;
            this.cbAngle.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbAngle, "cbAngle");
            this.cbAngle.FormattingEnabled = true;
            this.cbAngle.Items.AddRange(new object[] {
            resources.GetString("cbAngle.Items")});
            this.cbAngle.Name = "cbAngle";
            this.cbAngle.SelectedIndexChanged += new System.EventHandler(this.CbAngle_SelectedIndexChanged);
            // 
            // nudAngle
            // 
            this.nudAngle.BackColor = System.Drawing.Color.White;
            this.nudAngle.DecimalPlaces = 1;
            resources.ApplyResources(this.nudAngle, "nudAngle");
            this.nudAngle.Increment = new decimal(new int[] {
            36,
            0,
            0,
            65536});
            this.nudAngle.Maximum = new decimal(new int[] {
            360,
            0,
            0,
            0});
            this.nudAngle.Minimum = new decimal(new int[] {
            36,
            0,
            0,
            65536});
            this.nudAngle.Name = "nudAngle";
            this.nudAngle.Value = new decimal(new int[] {
            36,
            0,
            0,
            65536});
            this.nudAngle.ValueChanged += new System.EventHandler(this.NudValue_ValueChanged);
            // 
            // lAngleRange
            // 
            resources.ApplyResources(this.lAngleRange, "lAngleRange");
            this.lAngleRange.Name = "lAngleRange";
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.rbRotateCenter);
            this.panel2.Controls.Add(this.cbRotateWheel);
            this.panel2.Controls.Add(this.cbRotateCenter);
            this.panel2.Controls.Add(this.rbRotateWheel);
            resources.ApplyResources(this.panel2, "panel2");
            this.panel2.Name = "panel2";
            // 
            // RotatePanel
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.rbAngle);
            this.Controls.Add(this.cbAngle);
            this.Controls.Add(this.nudAngle);
            this.Controls.Add(this.lAngleRange);
            this.Controls.Add(this.cbFinishCommands);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.lFlowchart);
            this.Controls.Add(this.rbContiniously);
            this.Controls.Add(this.cbTime);
            this.Controls.Add(this.nudTime);
            this.Controls.Add(this.rbTime);
            this.Controls.Add(this.lTimeRange);
            this.Controls.Add(this.lSpeed);
            this.Controls.Add(this.nudSpeed);
            this.Controls.Add(this.lSpeedRange);
            this.Controls.Add(this.cbSpeed);
            this.Controls.Add(this.lRotation);
            resources.ApplyResources(this, "$this");
            this.Name = "RotatePanel";
            this.Controls.SetChildIndex(this.lActionName, 0);
            this.Controls.SetChildIndex(this.lRotation, 0);
            this.Controls.SetChildIndex(this.cbSpeed, 0);
            this.Controls.SetChildIndex(this.lSpeedRange, 0);
            this.Controls.SetChildIndex(this.nudSpeed, 0);
            this.Controls.SetChildIndex(this.lSpeed, 0);
            this.Controls.SetChildIndex(this.lTimeRange, 0);
            this.Controls.SetChildIndex(this.rbTime, 0);
            this.Controls.SetChildIndex(this.nudTime, 0);
            this.Controls.SetChildIndex(this.cbTime, 0);
            this.Controls.SetChildIndex(this.rbContiniously, 0);
            this.Controls.SetChildIndex(this.lFlowchart, 0);
            this.Controls.SetChildIndex(this.panel1, 0);
            this.Controls.SetChildIndex(this.cbFinishCommands, 0);
            this.Controls.SetChildIndex(this.lAngleRange, 0);
            this.Controls.SetChildIndex(this.nudAngle, 0);
            this.Controls.SetChildIndex(this.cbAngle, 0);
            this.Controls.SetChildIndex(this.rbAngle, 0);
            this.Controls.SetChildIndex(this.panel2, 0);
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label lSpeed;
        private Moway.Template.Controls.MowayRadioButton rbRotateCenter;
        private Moway.Template.Controls.MowayNumericUpDown nudSpeed;
        private System.Windows.Forms.Label lSpeedRange;
        private Moway.Template.Controls.MowayRadioButton rbRotateWheel;
        private Moway.Template.Controls.MowayComboBox cbSpeed;
        private System.Windows.Forms.Label lRotation;
        private Moway.Template.Controls.MowayComboBox cbRotateCenter;
        private Moway.Template.Controls.MowayComboBox cbRotateWheel;
        private Moway.Template.Controls.MowayCheckBox cbFinishCommands;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label lFlowchart;
        private Moway.Template.Controls.MowayRadioButton rbContiniously;
        private Moway.Template.Controls.MowayComboBox cbTime;
        private Moway.Template.Controls.MowayNumericUpDown nudTime;
        private Moway.Template.Controls.MowayRadioButton rbTime;
        private System.Windows.Forms.Label lTimeRange;
        private Moway.Template.Controls.MowayRadioButton rbAngle;
        private Moway.Template.Controls.MowayComboBox cbAngle;
        private Moway.Template.Controls.MowayNumericUpDown nudAngle;
        private System.Windows.Forms.Label lAngleRange;
        private System.Windows.Forms.Panel panel2;
    }
}
