namespace Moway.Project.GraphicProject.Boxes
{
    partial class ResultsBox
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ResultsBox));
            this.chDescription = new System.Windows.Forms.ColumnHeader();
            this.chDiagram = new System.Windows.Forms.ColumnHeader();
            this.pResultsListView = new System.Windows.Forms.Panel();
            this.lIcon = new System.Windows.Forms.Label();
            this.pContainer = new System.Windows.Forms.Panel();
            this.pItems = new System.Windows.Forms.Panel();
            this.lDiagram = new System.Windows.Forms.Label();
            this.lDescription = new System.Windows.Forms.Label();
            this.verticalScrollBar = new Moway.Template.Controls.MowayVScrollBar();
            this.bDelete = new Moway.Template.Controls.MowayButton();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottom)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbLeft)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTopRight)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTop)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTopLeft)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbRight)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottomRight)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottomLeft)).BeginInit();
            this.pResultsListView.SuspendLayout();
            this.pContainer.SuspendLayout();
            this.SuspendLayout();
            // 
            // lTittle
            // 
            resources.ApplyResources(this.lTittle, "lTittle");
            // 
            // pbBottom
            // 
            resources.ApplyResources(this.pbBottom, "pbBottom");
            // 
            // pbLeft
            // 
            resources.ApplyResources(this.pbLeft, "pbLeft");
            // 
            // pbTopRight
            // 
            resources.ApplyResources(this.pbTopRight, "pbTopRight");
            // 
            // pbTop
            // 
            resources.ApplyResources(this.pbTop, "pbTop");
            // 
            // pbRight
            // 
            resources.ApplyResources(this.pbRight, "pbRight");
            // 
            // pbBottomRight
            // 
            resources.ApplyResources(this.pbBottomRight, "pbBottomRight");
            // 
            // pbBottomLeft
            // 
            resources.ApplyResources(this.pbBottomLeft, "pbBottomLeft");
            // 
            // pResultsListView
            // 
            resources.ApplyResources(this.pResultsListView, "pResultsListView");
            this.pResultsListView.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            this.pResultsListView.Controls.Add(this.lIcon);
            this.pResultsListView.Controls.Add(this.pContainer);
            this.pResultsListView.Controls.Add(this.lDiagram);
            this.pResultsListView.Controls.Add(this.lDescription);
            this.pResultsListView.Controls.Add(this.verticalScrollBar);
            this.pResultsListView.Name = "pResultsListView";
            // 
            // lIcon
            // 
            this.lIcon.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(207)))), ((int)(((byte)(207)))));
            resources.ApplyResources(this.lIcon, "lIcon");
            this.lIcon.Name = "lIcon";
            // 
            // pContainer
            // 
            resources.ApplyResources(this.pContainer, "pContainer");
            this.pContainer.BackColor = System.Drawing.SystemColors.Window;
            this.pContainer.Controls.Add(this.pItems);
            this.pContainer.Name = "pContainer";
            this.pContainer.Click += new System.EventHandler(this.PContainer_Click);
            // 
            // pItems
            // 
            resources.ApplyResources(this.pItems, "pItems");
            this.pItems.Name = "pItems";
            this.pItems.SizeChanged += new System.EventHandler(this.PItems_SizeChanged);
            // 
            // lDiagram
            // 
            resources.ApplyResources(this.lDiagram, "lDiagram");
            this.lDiagram.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(207)))), ((int)(((byte)(207)))));
            this.lDiagram.Name = "lDiagram";
            // 
            // lDescription
            // 
            resources.ApplyResources(this.lDescription, "lDescription");
            this.lDescription.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(207)))), ((int)(((byte)(207)))));
            this.lDescription.Name = "lDescription";
            // 
            // verticalScrollBar
            // 
            resources.ApplyResources(this.verticalScrollBar, "verticalScrollBar");
            this.verticalScrollBar.BackColor = System.Drawing.Color.WhiteSmoke;
            this.verticalScrollBar.LargeChange = 5;
            this.verticalScrollBar.MaximumValue = 10;
            this.verticalScrollBar.Name = "verticalScrollBar";
            this.verticalScrollBar.SmallChange = 1;
            this.verticalScrollBar.Value = 0;
            this.verticalScrollBar.ValueChanged += new System.EventHandler(this.VerticalScrollBar_ValueChanged);
            // 
            // bDelete
            // 
            resources.ApplyResources(this.bDelete, "bDelete");
            this.bDelete.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(207)))), ((int)(((byte)(207)))));
            this.bDelete.FlatAppearance.BorderSize = 0;
            this.bDelete.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(207)))), ((int)(((byte)(207)))));
            this.bDelete.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(207)))), ((int)(((byte)(207)))));
            this.bDelete.Name = "bDelete";
            this.bDelete.UseVisualStyleBackColor = false;
            this.bDelete.Click += new System.EventHandler(this.BDelete_Click);
            // 
            // ResultsBox
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.bDelete);
            this.Controls.Add(this.pResultsListView);
            resources.ApplyResources(this, "$this");
            this.Name = "ResultsBox";
            this.Controls.SetChildIndex(this.pbTopLeft, 0);
            this.Controls.SetChildIndex(this.pbTop, 0);
            this.Controls.SetChildIndex(this.pbTopRight, 0);
            this.Controls.SetChildIndex(this.pbLeft, 0);
            this.Controls.SetChildIndex(this.pbBottomRight, 0);
            this.Controls.SetChildIndex(this.pbBottom, 0);
            this.Controls.SetChildIndex(this.pbBottomLeft, 0);
            this.Controls.SetChildIndex(this.lTittle, 0);
            this.Controls.SetChildIndex(this.pbRight, 0);
            this.Controls.SetChildIndex(this.pResultsListView, 0);
            this.Controls.SetChildIndex(this.bDelete, 0);
            ((System.ComponentModel.ISupportInitialize)(this.pbBottom)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbLeft)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTopRight)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTop)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTopLeft)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbRight)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottomRight)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottomLeft)).EndInit();
            this.pResultsListView.ResumeLayout(false);
            this.pContainer.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.ColumnHeader chDescription;
        private System.Windows.Forms.ColumnHeader chDiagram;
        private System.Windows.Forms.Panel pResultsListView;
        private System.Windows.Forms.Panel pContainer;
        private System.Windows.Forms.Panel pItems;
        private System.Windows.Forms.Label lDiagram;
        private System.Windows.Forms.Label lDescription;
        private Moway.Template.Controls.MowayVScrollBar verticalScrollBar;
        private System.Windows.Forms.Label lIcon;
        private Moway.Template.Controls.MowayButton bDelete;


    }
}
