namespace Moway.Project.GraphicProject.Boxes
{
    partial class ToolBox
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ToolBox));
            this.vScrollBar = new Moway.Template.Controls.MowayVScrollBar();
            this.pContainer = new System.Windows.Forms.Panel();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottom)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbLeft)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTopRight)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTop)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTopLeft)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbRight)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottomRight)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottomLeft)).BeginInit();
            this.SuspendLayout();
            // 
            // lTittle
            // 
            resources.ApplyResources(this.lTittle, "lTittle");
            // 
            // vScrollBar
            // 
            resources.ApplyResources(this.vScrollBar, "vScrollBar");
            this.vScrollBar.BackColor = System.Drawing.Color.WhiteSmoke;
            this.vScrollBar.LargeChange = 5;
            this.vScrollBar.MaximumValue = 10;
            this.vScrollBar.Name = "vScrollBar";
            this.vScrollBar.SmallChange = 1;
            this.vScrollBar.Value = 0;
            this.vScrollBar.ValueChanged += new System.EventHandler(this.vScrollBar_ValueChanged);
            // 
            // pContainer
            // 
            resources.ApplyResources(this.pContainer, "pContainer");
            this.pContainer.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(234)))), ((int)(((byte)(234)))));
            this.pContainer.Name = "pContainer";
            this.pContainer.SizeChanged += new System.EventHandler(this.pContainer_SizeChanged);
            // 
            // ToolBox
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.pContainer);
            this.Controls.Add(this.vScrollBar);
            this.Name = "ToolBox";
            this.Controls.SetChildIndex(this.vScrollBar, 0);
            this.Controls.SetChildIndex(this.pContainer, 0);
            this.Controls.SetChildIndex(this.pbTopLeft, 0);
            this.Controls.SetChildIndex(this.pbTop, 0);
            this.Controls.SetChildIndex(this.pbTopRight, 0);
            this.Controls.SetChildIndex(this.pbLeft, 0);
            this.Controls.SetChildIndex(this.pbBottomRight, 0);
            this.Controls.SetChildIndex(this.pbBottom, 0);
            this.Controls.SetChildIndex(this.pbBottomLeft, 0);
            this.Controls.SetChildIndex(this.lTittle, 0);
            this.Controls.SetChildIndex(this.pbRight, 0);
            ((System.ComponentModel.ISupportInitialize)(this.pbBottom)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbLeft)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTopRight)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTop)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTopLeft)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbRight)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottomRight)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottomLeft)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Moway.Template.Controls.MowayVScrollBar vScrollBar;
        private System.Windows.Forms.Panel pContainer;


    }
}
