namespace Moway.Project.GraphicProject.Boxes
{
    partial class WorkBox
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(WorkBox));
            this.tabPanel = new Moway.Template.Controls.PanelBorder();
            this.graphArea = new SdlDotNet.Windows.SurfaceControl();
            this.horizontalScroll = new Moway.Template.Controls.MowayHScrollBar();
            this.verticalScroll = new Moway.Template.Controls.MowayVScrollBar();
            this.tabButtonPlus = new Moway.Template.Controls.TabButton();
            this.graphAreaTimer = new System.Windows.Forms.Timer(this.components);
            this.toolTip = new System.Windows.Forms.ToolTip(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.pbBottom)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbLeft)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTopRight)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTop)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTopLeft)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbRight)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottomRight)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottomLeft)).BeginInit();
            this.tabPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.graphArea)).BeginInit();
            this.SuspendLayout();
            // 
            // lTittle
            // 
            resources.ApplyResources(this.lTittle, "lTittle");
            // 
            // tabPanel
            // 
            resources.ApplyResources(this.tabPanel, "tabPanel");
            this.tabPanel.Controls.Add(this.graphArea);
            this.tabPanel.Controls.Add(this.horizontalScroll);
            this.tabPanel.Controls.Add(this.verticalScroll);
            this.tabPanel.Name = "tabPanel";
            // 
            // graphArea
            // 
            resources.ApplyResources(this.graphArea, "graphArea");
            this.graphArea.AccessibleRole = System.Windows.Forms.AccessibleRole.Graphic;
            this.graphArea.BackColor = System.Drawing.Color.White;
            this.graphArea.Name = "graphArea";
            this.graphArea.TabStop = false;
            this.graphArea.DoubleClick += new System.EventHandler(this.GraphArea_DoubleClick);
            this.graphArea.MouseLeave += new System.EventHandler(this.GraphArea_MouseLeave);
            this.graphArea.MouseMove += new System.Windows.Forms.MouseEventHandler(this.GraphArea_MouseMove);
            this.graphArea.Click += new System.EventHandler(this.GraphArea_Click);
            this.graphArea.MouseDown += new System.Windows.Forms.MouseEventHandler(this.GraphArea_MouseDown);
            this.graphArea.MouseUp += new System.Windows.Forms.MouseEventHandler(this.GraphArea_MouseUp);
            this.graphArea.SizeChanged += new System.EventHandler(this.GraphArea_SizeChanged);
            this.graphArea.MouseEnter += new System.EventHandler(this.GraphArea_MouseEnter);
            // 
            // horizontalScroll
            // 
            resources.ApplyResources(this.horizontalScroll, "horizontalScroll");
            this.horizontalScroll.BackColor = System.Drawing.Color.WhiteSmoke;
            this.horizontalScroll.LargeChange = 5;
            this.horizontalScroll.MaximumValue = 3;
            this.horizontalScroll.Name = "horizontalScroll";
            this.horizontalScroll.SmallChange = 1;
            this.horizontalScroll.Value = 0;
            this.horizontalScroll.ValueChanged += new System.EventHandler(this.HorizontalScroll_ValueChanged);
            // 
            // verticalScroll
            // 
            resources.ApplyResources(this.verticalScroll, "verticalScroll");
            this.verticalScroll.BackColor = System.Drawing.Color.WhiteSmoke;
            this.verticalScroll.LargeChange = 5;
            this.verticalScroll.MaximumValue = 3;
            this.verticalScroll.Name = "verticalScroll";
            this.verticalScroll.SmallChange = 1;
            this.verticalScroll.Value = 0;
            this.verticalScroll.ValueChanged += new System.EventHandler(this.VerticalScroll_ValueChanged);
            // 
            // tabButtonPlus
            // 
            this.tabButtonPlus.BackColor = System.Drawing.Color.White;
            this.tabButtonPlus.Cursor = System.Windows.Forms.Cursors.Default;
            this.tabButtonPlus.FlatAppearance.BorderSize = 0;
            this.tabButtonPlus.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(248)))));
            this.tabButtonPlus.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(248)))), ((int)(((byte)(248)))));
            resources.ApplyResources(this.tabButtonPlus, "tabButtonPlus");
            this.tabButtonPlus.Name = "tabButtonPlus";
            this.tabButtonPlus.Selected = false;
            this.tabButtonPlus.TabStop = false;
            this.toolTip.SetToolTip(this.tabButtonPlus, resources.GetString("tabButtonPlus.ToolTip"));
            this.tabButtonPlus.UseVisualStyleBackColor = true;
            this.tabButtonPlus.Click += new System.EventHandler(this.TabButtonPlus_Click);
            // 
            // graphAreaTimer
            // 
            this.graphAreaTimer.Tick += new System.EventHandler(this.GraphAreaTimer_Tick);
            // 
            // WorkBox
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.tabPanel);
            this.Controls.Add(this.tabButtonPlus);
            this.Name = "WorkBox";
            this.Controls.SetChildIndex(this.pbTopLeft, 0);
            this.Controls.SetChildIndex(this.pbTop, 0);
            this.Controls.SetChildIndex(this.pbTopRight, 0);
            this.Controls.SetChildIndex(this.pbLeft, 0);
            this.Controls.SetChildIndex(this.pbBottomRight, 0);
            this.Controls.SetChildIndex(this.pbBottom, 0);
            this.Controls.SetChildIndex(this.pbBottomLeft, 0);
            this.Controls.SetChildIndex(this.pbRight, 0);
            this.Controls.SetChildIndex(this.lTittle, 0);
            this.Controls.SetChildIndex(this.tabButtonPlus, 0);
            this.Controls.SetChildIndex(this.tabPanel, 0);
            ((System.ComponentModel.ISupportInitialize)(this.pbBottom)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbLeft)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTopRight)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTop)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbTopLeft)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbRight)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottomRight)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbBottomLeft)).EndInit();
            this.tabPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.graphArea)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Moway.Template.Controls.PanelBorder tabPanel;
        private SdlDotNet.Windows.SurfaceControl graphArea;
        private Moway.Template.Controls.MowayHScrollBar horizontalScroll;
        private Moway.Template.Controls.MowayVScrollBar verticalScroll;
        private Moway.Template.Controls.TabButton tabButtonPlus;
        private System.Windows.Forms.Timer graphAreaTimer;
        private System.Windows.Forms.ToolTip toolTip;

    }
}
