//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//
//     Changes in this file may cause incorrect behavior and will be lost if
//     the code is rebuilt.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moway.Project.GraphicProject.Actions.Obstacle {
    using System;
    
    
    /// <summary>
    ///  Strongly typed resource class, to search for translated strings, etc.
    /// </summary>
    // StronglyTypedResourceBuilder automatically generated this class
    //  through a tool such as ResGen or Visual Studio.
    // To add or remove a member, edit the .ResX file and then run ResGen again
    // with the / str option or recompile your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ObstacleMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObstacleMessages() {
        }
        
        /// <summary>
        ///  Returns the ResourceManager instance cached used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moway.Project.GraphicProject.Actions.Obstacle.ObstacleMessages", typeof(ObstacleMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Replaces the CurrentUICulture property of the current thread
        ///   for all resource searches using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Ouput is always true..
        /// </summary>
        internal static string ALWAYS_TRUE {
            get {
                return ResourceManager.GetString("ALWAYS_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to and.
        /// </summary>
        internal static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to detects an object.
        /// </summary>
        internal static string DETECT {
            get {
                return ResourceManager.GetString("DETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to False.
        /// </summary>
        internal static string FALSE {
            get {
                return ResourceManager.GetString("FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to If.
        /// </summary>
        internal static string IF {
            get {
                return ResourceManager.GetString("IF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Left Central Sensor.
        /// </summary>
        internal static string LEFT_CENTRAL_SENSOR {
            get {
                return ResourceManager.GetString("LEFT_CENTRAL_SENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Left Side Sensor.
        /// </summary>
        internal static string LEFT_SIDE_SENSOR {
            get {
                return ResourceManager.GetString("LEFT_SIDE_SENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to doesn&apos;t detect any object.
        /// </summary>
        internal static string NOT_DETECT {
            get {
                return ResourceManager.GetString("NOT_DETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to or.
        /// </summary>
        internal static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Otherwise.
        /// </summary>
        internal static string OTHERWISE {
            get {
                return ResourceManager.GetString("OTHERWISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Right Central Sensor.
        /// </summary>
        internal static string RIGHT_CENTRAL_SENSOR {
            get {
                return ResourceManager.GetString("RIGHT_CENTRAL_SENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Right Side Sensor.
        /// </summary>
        internal static string RIGHT_SIDE_SENSOR {
            get {
                return ResourceManager.GetString("RIGHT_SIDE_SENSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to True.
        /// </summary>
        internal static string TRUE {
            get {
                return ResourceManager.GetString("TRUE", resourceCulture);
            }
        }
    }
}
