namespace Moway.Project.GraphicProject.Actions.Reset
{
    partial class ResetPanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ResetPanel));
            this.cbDistance = new Moway.Template.Controls.MowayCheckBox();
            this.cbTime = new Moway.Template.Controls.MowayCheckBox();
            this.SuspendLayout();
            // 
            // lActionName
            // 
            resources.ApplyResources(this.lActionName, "lActionName");
            // 
            // cbDistance
            // 
            resources.ApplyResources(this.cbDistance, "cbDistance");
            this.cbDistance.Name = "cbDistance";
            this.cbDistance.UseVisualStyleBackColor = true;
            this.cbDistance.CheckedChanged += new System.EventHandler(this.cbReset_CheckedChanged);
            // 
            // cbTime
            // 
            resources.ApplyResources(this.cbTime, "cbTime");
            this.cbTime.Name = "cbTime";
            this.cbTime.UseVisualStyleBackColor = true;
            this.cbTime.CheckedChanged += new System.EventHandler(this.cbReset_CheckedChanged);
            // 
            // ResetPanel
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.cbDistance);
            this.Controls.Add(this.cbTime);
            resources.ApplyResources(this, "$this");
            this.Name = "ResetPanel";
            this.Controls.SetChildIndex(this.lActionName, 0);
            this.Controls.SetChildIndex(this.cbTime, 0);
            this.Controls.SetChildIndex(this.cbDistance, 0);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Moway.Template.Controls.MowayCheckBox cbDistance;
        private Moway.Template.Controls.MowayCheckBox cbTime;
    }
}
