//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//
//     Changes in this file may cause incorrect behavior and will be lost if
//     the code is rebuilt.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moway.Project.GraphicProject.Processes {
    using System;
    
    
    /// <summary>
    ///  Strongly typed resource class, to search for translated strings, etc.
    /// </summary>
    // StronglyTypedResourceBuilder automatically generated this class
    //  through a tool such as ResGen or Visual Studio.
    // To add or remove a member, edit the .ResX file and then run ResGen again
    // with the / str option or recompile your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcessMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcessMessages() {
        }
        
        /// <summary>
        ///  Returns the ResourceManager instance cached used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moway.Project.GraphicProject.Processes.ProcessMessages", typeof(ProcessMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Replaces the CurrentUICulture property of the current thread
        ///   for all resource searches using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Can not read the file.
        /// </summary>
        internal static string ACCES_DENIED {
            get {
                return ResourceManager.GetString("ACCES_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Found errors in the diagrams.
        /// </summary>
        internal static string CHECKDIAGRAM_ERROR {
            get {
                return ResourceManager.GetString("CHECKDIAGRAM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Diagrams are correct.
        /// </summary>
        internal static string CHECKDIAGRAM_OK {
            get {
                return ResourceManager.GetString("CHECKDIAGRAM_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Found warning in the diagrams.
        /// </summary>
        internal static string CHECKDIAGRAM_WARNING {
            get {
                return ResourceManager.GetString("CHECKDIAGRAM_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Errors occurred while compiling.
        /// </summary>
        internal static string COMPILECODE_ERROR {
            get {
                return ResourceManager.GetString("COMPILECODE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to The code has been properly compiled.
        /// </summary>
        internal static string COMPILECODE_OK {
            get {
                return ResourceManager.GetString("COMPILECODE_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Do you want to continue anyway?.
        /// </summary>
        internal static string CONTINUE {
            get {
                return ResourceManager.GetString("CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to File not found.
        /// </summary>
        internal static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to There was an error while generating the code.
        /// </summary>
        internal static string GENERATECODE_ERROR {
            get {
                return ResourceManager.GetString("GENERATECODE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to The code has been generated successfully.
        /// </summary>
        internal static string GENERATECODE_OK {
            get {
                return ResourceManager.GetString("GENERATECODE_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to HEX file is too large for mOway 2.0.1 version..
        /// </summary>
        internal static string HEX_TOO_LARGE {
            get {
                return ResourceManager.GetString("HEX_TOO_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to HEX file is too large for mOway 2.0.1 version..
        /// </summary>
        internal static string HEX_TOO_LARGE_201 {
            get {
                return ResourceManager.GetString("HEX_TOO_LARGE_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to HEX file is too large for mOway 2.0.2 version..
        /// </summary>
        internal static string HEX_TOO_LARGE_202 {
            get {
                return ResourceManager.GetString("HEX_TOO_LARGE_202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to mOway memory error.
        /// </summary>
        internal static string MEMORY_ERROR {
            get {
                return ResourceManager.GetString("MEMORY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to mOway robot is busy. Restart it.
        /// </summary>
        internal static string MOWAY_BUSY {
            get {
                return ResourceManager.GetString("MOWAY_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to mOway robot is disconnected.
        /// </summary>
        internal static string MOWAY_DISCONNECTED {
            get {
                return ResourceManager.GetString("MOWAY_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Program mOway.
        /// </summary>
        internal static string PROGRAM {
            get {
                return ResourceManager.GetString("PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Programming mOway.
        /// </summary>
        internal static string PROGRAMMING_MOWAY {
            get {
                return ResourceManager.GetString("PROGRAMMING_MOWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Has failed to program the robot.
        /// </summary>
        internal static string PROGRAMMOWAY_ERROR {
            get {
                return ResourceManager.GetString("PROGRAMMOWAY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to The robot has been programmed correctly.
        /// </summary>
        internal static string PROGRAMMOWAY_OK {
            get {
                return ResourceManager.GetString("PROGRAMMOWAY_OK", resourceCulture);
            }
        }
    }
}
