namespace Moway.Project.GraphicProject.Actions.Lights
{
    partial class LightsPanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(LightsPanel));
            this.lFront = new System.Windows.Forms.Label();
            this.lBrake = new System.Windows.Forms.Label();
            this.lTopGreen = new System.Windows.Forms.Label();
            this.lTopRed = new System.Windows.Forms.Label();
            this.cbBreak = new Moway.Template.Controls.MowayComboBox();
            this.cbFront = new Moway.Template.Controls.MowayComboBox();
            this.cbTopGreen = new Moway.Template.Controls.MowayComboBox();
            this.cbTopRed = new Moway.Template.Controls.MowayComboBox();
            this.SuspendLayout();
            // 
            // lActionName
            // 
            resources.ApplyResources(this.lActionName, "lActionName");
            // 
            // lFront
            // 
            resources.ApplyResources(this.lFront, "lFront");
            this.lFront.Name = "lFront";
            // 
            // lBrake
            // 
            resources.ApplyResources(this.lBrake, "lBrake");
            this.lBrake.Name = "lBrake";
            // 
            // lTopGreen
            // 
            resources.ApplyResources(this.lTopGreen, "lTopGreen");
            this.lTopGreen.Name = "lTopGreen";
            // 
            // lTopRed
            // 
            resources.ApplyResources(this.lTopRed, "lTopRed");
            this.lTopRed.Name = "lTopRed";
            // 
            // cbBreak
            // 
            this.cbBreak.BackColor = System.Drawing.Color.White;
            this.cbBreak.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbBreak.DropDownHeight = 100;
            this.cbBreak.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbBreak, "cbBreak");
            this.cbBreak.FormattingEnabled = true;
            this.cbBreak.Items.AddRange(new object[] {
            resources.GetString("cbBreak.Items"),
            resources.GetString("cbBreak.Items1"),
            resources.GetString("cbBreak.Items2"),
            resources.GetString("cbBreak.Items3")});
            this.cbBreak.Name = "cbBreak";
            this.cbBreak.SelectedIndexChanged += new System.EventHandler(this.ComboBox_SelectedIndexChanged);
            // 
            // cbFront
            // 
            this.cbFront.BackColor = System.Drawing.Color.White;
            this.cbFront.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbFront.DropDownHeight = 100;
            this.cbFront.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbFront, "cbFront");
            this.cbFront.FormattingEnabled = true;
            this.cbFront.Items.AddRange(new object[] {
            resources.GetString("cbFront.Items"),
            resources.GetString("cbFront.Items1"),
            resources.GetString("cbFront.Items2"),
            resources.GetString("cbFront.Items3")});
            this.cbFront.Name = "cbFront";
            this.cbFront.SelectedIndexChanged += new System.EventHandler(this.ComboBox_SelectedIndexChanged);
            // 
            // cbTopGreen
            // 
            this.cbTopGreen.BackColor = System.Drawing.Color.White;
            this.cbTopGreen.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbTopGreen.DropDownHeight = 100;
            this.cbTopGreen.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbTopGreen, "cbTopGreen");
            this.cbTopGreen.FormattingEnabled = true;
            this.cbTopGreen.Items.AddRange(new object[] {
            resources.GetString("cbTopGreen.Items"),
            resources.GetString("cbTopGreen.Items1"),
            resources.GetString("cbTopGreen.Items2"),
            resources.GetString("cbTopGreen.Items3")});
            this.cbTopGreen.Name = "cbTopGreen";
            this.cbTopGreen.SelectedIndexChanged += new System.EventHandler(this.ComboBox_SelectedIndexChanged);
            // 
            // cbTopRed
            // 
            this.cbTopRed.BackColor = System.Drawing.Color.White;
            this.cbTopRed.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbTopRed.DropDownHeight = 100;
            this.cbTopRed.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbTopRed, "cbTopRed");
            this.cbTopRed.FormattingEnabled = true;
            this.cbTopRed.Items.AddRange(new object[] {
            resources.GetString("cbTopRed.Items"),
            resources.GetString("cbTopRed.Items1"),
            resources.GetString("cbTopRed.Items2"),
            resources.GetString("cbTopRed.Items3")});
            this.cbTopRed.Name = "cbTopRed";
            this.cbTopRed.SelectedIndexChanged += new System.EventHandler(this.ComboBox_SelectedIndexChanged);
            // 
            // LightsPanel
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(234)))), ((int)(((byte)(234)))));
            this.Controls.Add(this.cbBreak);
            this.Controls.Add(this.cbFront);
            this.Controls.Add(this.cbTopGreen);
            this.Controls.Add(this.lFront);
            this.Controls.Add(this.lTopGreen);
            this.Controls.Add(this.lBrake);
            this.Controls.Add(this.cbTopRed);
            this.Controls.Add(this.lTopRed);
            resources.ApplyResources(this, "$this");
            this.Name = "LightsPanel";
            this.Controls.SetChildIndex(this.lTopRed, 0);
            this.Controls.SetChildIndex(this.cbTopRed, 0);
            this.Controls.SetChildIndex(this.lBrake, 0);
            this.Controls.SetChildIndex(this.lTopGreen, 0);
            this.Controls.SetChildIndex(this.lFront, 0);
            this.Controls.SetChildIndex(this.cbTopGreen, 0);
            this.Controls.SetChildIndex(this.cbFront, 0);
            this.Controls.SetChildIndex(this.cbBreak, 0);
            this.Controls.SetChildIndex(this.lActionName, 0);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Moway.Template.Controls.MowayComboBox cbBreak;
        private System.Windows.Forms.Label lFront;
        private System.Windows.Forms.Label lBrake;
        private Moway.Template.Controls.MowayComboBox cbFront;
        private System.Windows.Forms.Label lTopGreen;
        private System.Windows.Forms.Label lTopRed;
        private Moway.Template.Controls.MowayComboBox cbTopGreen;
        private Moway.Template.Controls.MowayComboBox cbTopRed;
    }
}
