namespace Moway.Project.GraphicProject.Actions.Math
{
    partial class MathPanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MathPanel));
            this.cbResult = new Moway.Template.Controls.MowayComboBox();
            this.cbOperand = new Moway.Template.Controls.MowayComboBox();
            this.nudOperandValue = new Moway.Template.Controls.MowayNumericUpDown();
            this.cbOperator = new Moway.Template.Controls.MowayComboBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.lDistanceRange = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // lActionName
            // 
            resources.ApplyResources(this.lActionName, "lActionName");
            // 
            // cbResult
            // 
            this.cbResult.BackColor = System.Drawing.Color.White;
            this.cbResult.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbResult.DropDownHeight = 100;
            this.cbResult.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbResult, "cbResult");
            this.cbResult.FormattingEnabled = true;
            this.cbResult.Name = "cbResult";
            this.cbResult.SelectedIndexChanged += new System.EventHandler(this.ComboBox_SelectedIndexChanged);
            // 
            // cbOperand
            // 
            this.cbOperand.BackColor = System.Drawing.Color.White;
            this.cbOperand.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbOperand.DropDownHeight = 100;
            this.cbOperand.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbOperand, "cbOperand");
            this.cbOperand.FormattingEnabled = true;
            this.cbOperand.Items.AddRange(new object[] {
            resources.GetString("cbOperand.Items")});
            this.cbOperand.Name = "cbOperand";
            this.cbOperand.SelectedIndexChanged += new System.EventHandler(this.CbOperand_SelectedIndexChanged);
            // 
            // nudOperandValue
            // 
            this.nudOperandValue.BackColor = System.Drawing.Color.White;
            this.nudOperandValue.DecimalPlaces = 0;
            resources.ApplyResources(this.nudOperandValue, "nudOperandValue");
            this.nudOperandValue.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudOperandValue.Maximum = new decimal(new int[] {
            255,
            0,
            0,
            0});
            this.nudOperandValue.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudOperandValue.Name = "nudOperandValue";
            this.nudOperandValue.Value = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudOperandValue.ValueChanged += new System.EventHandler(this.NudOperandValue_ValueChanged);
            // 
            // cbOperator
            // 
            this.cbOperator.BackColor = System.Drawing.Color.White;
            this.cbOperator.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbOperator.DropDownHeight = 100;
            this.cbOperator.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbOperator, "cbOperator");
            this.cbOperator.FormattingEnabled = true;
            this.cbOperator.Items.AddRange(new object[] {
            resources.GetString("cbOperator.Items"),
            resources.GetString("cbOperator.Items1")});
            this.cbOperator.Name = "cbOperator";
            this.cbOperator.SelectedIndexChanged += new System.EventHandler(this.ComboBox_SelectedIndexChanged);
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // label2
            // 
            resources.ApplyResources(this.label2, "label2");
            this.label2.Name = "label2";
            // 
            // label3
            // 
            resources.ApplyResources(this.label3, "label3");
            this.label3.Name = "label3";
            // 
            // lDistanceRange
            // 
            resources.ApplyResources(this.lDistanceRange, "lDistanceRange");
            this.lDistanceRange.Name = "lDistanceRange";
            // 
            // MathPanel
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.lDistanceRange);
            this.Controls.Add(this.cbResult);
            this.Controls.Add(this.cbOperand);
            this.Controls.Add(this.nudOperandValue);
            this.Controls.Add(this.cbOperator);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Name = "MathPanel";
            this.Controls.SetChildIndex(this.label1, 0);
            this.Controls.SetChildIndex(this.label2, 0);
            this.Controls.SetChildIndex(this.label3, 0);
            this.Controls.SetChildIndex(this.lActionName, 0);
            this.Controls.SetChildIndex(this.cbOperator, 0);
            this.Controls.SetChildIndex(this.nudOperandValue, 0);
            this.Controls.SetChildIndex(this.cbOperand, 0);
            this.Controls.SetChildIndex(this.cbResult, 0);
            this.Controls.SetChildIndex(this.lDistanceRange, 0);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Moway.Template.Controls.MowayComboBox cbResult;
        private Moway.Template.Controls.MowayComboBox cbOperand;
        private Moway.Template.Controls.MowayNumericUpDown nudOperandValue;
        private Moway.Template.Controls.MowayComboBox cbOperator;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label lDistanceRange;
    }
}
