//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//
//     Changes in this file may cause incorrect behavior and will be lost if
//     the code is rebuilt.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moway {
    using System;
    
    
    /// <summary>
    ///  Strongly typed resource class, to search for translated strings, etc.
    /// </summary>
    // StronglyTypedResourceBuilder automatically generated this class
    //  through a tool such as ResGen or Visual Studio.
    // To add or remove a member, edit the .ResX file and then run ResGen again
    // with the / str option or recompile your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainMessages() {
        }
        
        /// <summary>
        ///  Returns the ResourceManager instance cached used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moway.MainMessages", typeof(MainMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Replaces the CurrentUICulture property of the current thread
        ///   for all resource searches using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to MowayWorld has to restart to change the language. Do you want to close MowayWorld?.
        /// </summary>
        internal static string CHANGE_LANGUAGE {
            get {
                return ResourceManager.GetString("CHANGE_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Change Language.
        /// </summary>
        internal static string CHANGE_LANGUAGE_TITLE {
            get {
                return ResourceManager.GetString("CHANGE_LANGUAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Connected.
        /// </summary>
        internal static string CONNECTED {
            get {
                return ResourceManager.GetString("CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Are you sure you want to continue?.
        /// </summary>
        internal static string CONTINUE {
            get {
                return ResourceManager.GetString("CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Disconnected.
        /// </summary>
        internal static string DISCONNECTED {
            get {
                return ResourceManager.GetString("DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Open Project.
        /// </summary>
        internal static string OPEN_PROJECT {
            get {
                return ResourceManager.GetString("OPEN_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to The project doesn&apos;t have files directory.
        /// </summary>
        internal static string OPEN_PROJECT_DIRECTORY_ERROR {
            get {
                return ResourceManager.GetString("OPEN_PROJECT_DIRECTORY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Can&apos;t open project file.
        /// </summary>
        internal static string OPEN_PROJECT_ERROR {
            get {
                return ResourceManager.GetString("OPEN_PROJECT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to The current project is not saved..
        /// </summary>
        internal static string PROJECT_NOT_SAVE {
            get {
                return ResourceManager.GetString("PROJECT_NOT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to RC Cam Control.
        /// </summary>
        internal static string RC_CAM_CONTROL {
            get {
                return ResourceManager.GetString("RC_CAM_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to If you open RC Cam Control, MowayWorld will be closed..
        /// </summary>
        internal static string RC_CAM_WARNING_CLOSE {
            get {
                return ResourceManager.GetString("RC_CAM_WARNING_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to To use RC Cam Control need to download a program to mOway..
        /// </summary>
        internal static string RC_CAM_WARNING_PROGRAM {
            get {
                return ResourceManager.GetString("RC_CAM_WARNING_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to RC Control.
        /// </summary>
        internal static string RC_CONTROL {
            get {
                return ResourceManager.GetString("RC_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Do you want to program one mOway?.
        /// </summary>
        internal static string RC_PROGRAM {
            get {
                return ResourceManager.GetString("RC_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to The mOway could not be programed..
        /// </summary>
        internal static string RC_PROGRAM_ERROR {
            get {
                return ResourceManager.GetString("RC_PROGRAM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Do you want to try again?.
        /// </summary>
        internal static string RC_TRY {
            get {
                return ResourceManager.GetString("RC_TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to If you open RC Control, MowayWorld will be closed..
        /// </summary>
        internal static string RC_WARNING_CLOSE {
            get {
                return ResourceManager.GetString("RC_WARNING_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Save changes?.
        /// </summary>
        internal static string SAVE_CHANGES {
            get {
                return ResourceManager.GetString("SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to Save Project.
        /// </summary>
        internal static string SAVE_PROJECT {
            get {
                return ResourceManager.GetString("SAVE_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to MowayWorld update.
        /// </summary>
        internal static string UPDATER {
            get {
                return ResourceManager.GetString("UPDATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for a translated string similar to MowayWorld Updater not found. You can download new software version from http://www.moway-robot.com/.
        /// </summary>
        internal static string UPDATER_ERROR {
            get {
                return ResourceManager.GetString("UPDATER_ERROR", resourceCulture);
            }
        }
    }
}
