namespace Moway.Simulator.Communications
{
    partial class CommunicationPanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CommunicationPanel));
            this.bDelete = new Moway.Template.Controls.MowayButton();
            this.bClear = new Moway.Template.Controls.MowayButton();
            this.lSendState = new System.Windows.Forms.Label();
            this.separator = new System.Windows.Forms.Panel();
            this.lbMessages = new System.Windows.Forms.ListBox();
            this.lTransmiterData = new System.Windows.Forms.Label();
            this.bSend = new Moway.Template.Controls.MowayButton();
            this.tbData1 = new Moway.Template.Controls.MowayTextBox();
            this.tbData2 = new Moway.Template.Controls.MowayTextBox();
            this.tbData3 = new Moway.Template.Controls.MowayTextBox();
            this.tbData4 = new Moway.Template.Controls.MowayTextBox();
            this.tbData5 = new Moway.Template.Controls.MowayTextBox();
            this.tbData6 = new Moway.Template.Controls.MowayTextBox();
            this.tbData7 = new Moway.Template.Controls.MowayTextBox();
            this.tbData0 = new Moway.Template.Controls.MowayTextBox();
            this.nudChannel = new Moway.Template.Controls.MowayNumericUpDown();
            this.lChannel = new System.Windows.Forms.Label();
            this.lEmiterDirection = new System.Windows.Forms.Label();
            this.nudDirection = new Moway.Template.Controls.MowayNumericUpDown();
            this.l0 = new System.Windows.Forms.Label();
            this.l7 = new System.Windows.Forms.Label();
            this.tSendState = new System.Windows.Forms.Timer(this.components);
            this.toolTip = new Moway.Template.Controls.MowayToolTip();
            this.lRfusbConfig = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // bDelete
            // 
            resources.ApplyResources(this.bDelete, "bDelete");
            this.bDelete.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            this.bDelete.FlatAppearance.BorderSize = 0;
            this.bDelete.Name = "bDelete";
            this.bDelete.UseVisualStyleBackColor = true;
            this.bDelete.Click += new System.EventHandler(this.BDelete_Click);
            // 
            // bClear
            // 
            resources.ApplyResources(this.bClear, "bClear");
            this.bClear.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            this.bClear.FlatAppearance.BorderSize = 0;
            this.bClear.Name = "bClear";
            this.bClear.UseVisualStyleBackColor = true;
            this.bClear.Click += new System.EventHandler(this.BClear_Click);
            // 
            // lSendState
            // 
            resources.ApplyResources(this.lSendState, "lSendState");
            this.lSendState.Name = "lSendState";
            // 
            // separator
            // 
            this.separator.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            resources.ApplyResources(this.separator, "separator");
            this.separator.Name = "separator";
            // 
            // lbMessages
            // 
            this.lbMessages.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lbMessages.FormattingEnabled = true;
            resources.ApplyResources(this.lbMessages, "lbMessages");
            this.lbMessages.Name = "lbMessages";
            this.lbMessages.SelectedIndexChanged += new System.EventHandler(this.LbMessages_SelectedIndexChanged);
            // 
            // lTransmiterData
            // 
            resources.ApplyResources(this.lTransmiterData, "lTransmiterData");
            this.lTransmiterData.Name = "lTransmiterData";
            // 
            // bSend
            // 
            this.bSend.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            resources.ApplyResources(this.bSend, "bSend");
            this.bSend.Name = "bSend";
            this.bSend.UseVisualStyleBackColor = true;
            this.bSend.Click += new System.EventHandler(this.BSend_Click);
            // 
            // tbData1
            // 
            this.tbData1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            resources.ApplyResources(this.tbData1, "tbData1");
            this.tbData1.Name = "tbData1";
            // 
            // tbData2
            // 
            this.tbData2.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            resources.ApplyResources(this.tbData2, "tbData2");
            this.tbData2.Name = "tbData2";
            // 
            // tbData3
            // 
            this.tbData3.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            resources.ApplyResources(this.tbData3, "tbData3");
            this.tbData3.Name = "tbData3";
            // 
            // tbData4
            // 
            this.tbData4.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            resources.ApplyResources(this.tbData4, "tbData4");
            this.tbData4.Name = "tbData4";
            // 
            // tbData5
            // 
            this.tbData5.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            resources.ApplyResources(this.tbData5, "tbData5");
            this.tbData5.Name = "tbData5";
            // 
            // tbData6
            // 
            this.tbData6.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            resources.ApplyResources(this.tbData6, "tbData6");
            this.tbData6.Name = "tbData6";
            // 
            // tbData7
            // 
            this.tbData7.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            resources.ApplyResources(this.tbData7, "tbData7");
            this.tbData7.Name = "tbData7";
            // 
            // tbData0
            // 
            this.tbData0.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            resources.ApplyResources(this.tbData0, "tbData0");
            this.tbData0.Name = "tbData0";
            // 
            // nudChannel
            // 
            this.nudChannel.BackColor = System.Drawing.Color.White;
            this.nudChannel.DecimalPlaces = 0;
            resources.ApplyResources(this.nudChannel, "nudChannel");
            this.nudChannel.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudChannel.Maximum = new decimal(new int[] {
            125,
            0,
            0,
            0});
            this.nudChannel.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudChannel.Name = "nudChannel";
            this.nudChannel.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            // 
            // lChannel
            // 
            resources.ApplyResources(this.lChannel, "lChannel");
            this.lChannel.Name = "lChannel";
            // 
            // lEmiterDirection
            // 
            resources.ApplyResources(this.lEmiterDirection, "lEmiterDirection");
            this.lEmiterDirection.Name = "lEmiterDirection";
            // 
            // nudDirection
            // 
            this.nudDirection.BackColor = System.Drawing.Color.White;
            this.nudDirection.DecimalPlaces = 0;
            resources.ApplyResources(this.nudDirection, "nudDirection");
            this.nudDirection.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudDirection.Maximum = new decimal(new int[] {
            255,
            0,
            0,
            0});
            this.nudDirection.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudDirection.Name = "nudDirection";
            this.nudDirection.Value = new decimal(new int[] {
            0,
            0,
            0,
            0});
            // 
            // l0
            // 
            resources.ApplyResources(this.l0, "l0");
            this.l0.Name = "l0";
            // 
            // l7
            // 
            resources.ApplyResources(this.l7, "l7");
            this.l7.Name = "l7";
            // 
            // tSendState
            // 
            this.tSendState.Interval = 5000;
            this.tSendState.Tick += new System.EventHandler(this.TSendState_Tick);
            // 
            // lRfusbConfig
            // 
            resources.ApplyResources(this.lRfusbConfig, "lRfusbConfig");
            this.lRfusbConfig.Name = "lRfusbConfig";
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // CommunicationPanel
            // 
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.label1);
            this.Controls.Add(this.lRfusbConfig);
            this.Controls.Add(this.bDelete);
            this.Controls.Add(this.bClear);
            this.Controls.Add(this.lSendState);
            this.Controls.Add(this.separator);
            this.Controls.Add(this.lbMessages);
            this.Controls.Add(this.lTransmiterData);
            this.Controls.Add(this.bSend);
            this.Controls.Add(this.tbData1);
            this.Controls.Add(this.tbData2);
            this.Controls.Add(this.tbData3);
            this.Controls.Add(this.tbData4);
            this.Controls.Add(this.tbData5);
            this.Controls.Add(this.tbData6);
            this.Controls.Add(this.tbData7);
            this.Controls.Add(this.tbData0);
            this.Controls.Add(this.nudChannel);
            this.Controls.Add(this.lChannel);
            this.Controls.Add(this.lEmiterDirection);
            this.Controls.Add(this.nudDirection);
            this.Controls.Add(this.l0);
            this.Controls.Add(this.l7);
            this.Name = "CommunicationPanel";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Moway.Template.Controls.MowayButton bDelete;
        private Moway.Template.Controls.MowayButton bClear;
        private System.Windows.Forms.Label lSendState;
        private System.Windows.Forms.Panel separator;
        private System.Windows.Forms.ListBox lbMessages;
        private System.Windows.Forms.Label lTransmiterData;
        private Moway.Template.Controls.MowayButton bSend;
        private Moway.Template.Controls.MowayTextBox tbData1;
        private Moway.Template.Controls.MowayTextBox tbData2;
        private Moway.Template.Controls.MowayTextBox tbData3;
        private Moway.Template.Controls.MowayTextBox tbData4;
        private Moway.Template.Controls.MowayTextBox tbData5;
        private Moway.Template.Controls.MowayTextBox tbData6;
        private Moway.Template.Controls.MowayTextBox tbData7;
        private Moway.Template.Controls.MowayTextBox tbData0;
        private Moway.Template.Controls.MowayNumericUpDown nudChannel;
        private System.Windows.Forms.Label lChannel;
        private System.Windows.Forms.Label lEmiterDirection;
        private Moway.Template.Controls.MowayNumericUpDown nudDirection;
        private System.Windows.Forms.Label l0;
        private System.Windows.Forms.Label l7;
        private System.Windows.Forms.Timer tSendState;
        private Moway.Template.Controls.MowayToolTip toolTip;
        private System.Windows.Forms.Label lRfusbConfig;
        private System.Windows.Forms.Label label1;
    }
}
