namespace Moway.Project.GraphicProject.Actions.CompareLine
{
    partial class CompareLinePanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CompareLinePanel));
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.cbOperator = new Moway.Template.Controls.MowayComboBox();
            this.cbCompareVariable = new Moway.Template.Controls.MowayComboBox();
            this.rbRightSensor = new Moway.Template.Controls.MowayRadioButton();
            this.rbLeftSensor = new Moway.Template.Controls.MowayRadioButton();
            this.label3 = new System.Windows.Forms.Label();
            this.nudCompareValue = new Moway.Template.Controls.MowayNumericUpDown();
            this.lValueHelp = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // lActionName
            // 
            this.lActionName.AccessibleDescription = null;
            this.lActionName.AccessibleName = null;
            resources.ApplyResources(this.lActionName, "lActionName");
            // 
            // label2
            // 
            this.label2.AccessibleDescription = null;
            this.label2.AccessibleName = null;
            resources.ApplyResources(this.label2, "label2");
            this.label2.Font = null;
            this.label2.Name = "label2";
            // 
            // label1
            // 
            this.label1.AccessibleDescription = null;
            this.label1.AccessibleName = null;
            resources.ApplyResources(this.label1, "label1");
            this.label1.Font = null;
            this.label1.Name = "label1";
            // 
            // cbOperator
            // 
            this.cbOperator.AccessibleDescription = null;
            this.cbOperator.AccessibleName = null;
            resources.ApplyResources(this.cbOperator, "cbOperator");
            this.cbOperator.BackColor = System.Drawing.Color.White;
            this.cbOperator.BackgroundImage = null;
            this.cbOperator.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbOperator.DropDownHeight = 100;
            this.cbOperator.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbOperator.FormattingEnabled = true;
            this.cbOperator.Items.AddRange(new object[] {
            resources.GetString("cbOperator.Items"),
            resources.GetString("cbOperator.Items1"),
            resources.GetString("cbOperator.Items2"),
            resources.GetString("cbOperator.Items3"),
            resources.GetString("cbOperator.Items4"),
            resources.GetString("cbOperator.Items5")});
            this.cbOperator.Name = "cbOperator";
            this.cbOperator.SelectedIndexChanged += new System.EventHandler(this.CbOperator_SelectedIndexChanged);
            // 
            // cbCompareVariable
            // 
            this.cbCompareVariable.AccessibleDescription = null;
            this.cbCompareVariable.AccessibleName = null;
            resources.ApplyResources(this.cbCompareVariable, "cbCompareVariable");
            this.cbCompareVariable.BackColor = System.Drawing.Color.White;
            this.cbCompareVariable.BackgroundImage = null;
            this.cbCompareVariable.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbCompareVariable.DropDownHeight = 100;
            this.cbCompareVariable.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbCompareVariable.FormattingEnabled = true;
            this.cbCompareVariable.Items.AddRange(new object[] {
            resources.GetString("cbCompareVariable.Items")});
            this.cbCompareVariable.Name = "cbCompareVariable";
            this.cbCompareVariable.SelectedIndexChanged += new System.EventHandler(this.CbCompareVariable_SelectedIndexChanged);
            // 
            // rbRightSensor
            // 
            this.rbRightSensor.AccessibleDescription = null;
            this.rbRightSensor.AccessibleName = null;
            resources.ApplyResources(this.rbRightSensor, "rbRightSensor");
            this.rbRightSensor.BackgroundImage = null;
            this.rbRightSensor.Checked = true;
            this.rbRightSensor.Name = "rbRightSensor";
            this.rbRightSensor.TabStop = true;
            this.rbRightSensor.UseVisualStyleBackColor = true;
            this.rbRightSensor.CheckedChanged += new System.EventHandler(this.RbSensor_CheckedChanged);
            // 
            // rbLeftSensor
            // 
            this.rbLeftSensor.AccessibleDescription = null;
            this.rbLeftSensor.AccessibleName = null;
            resources.ApplyResources(this.rbLeftSensor, "rbLeftSensor");
            this.rbLeftSensor.BackgroundImage = null;
            this.rbLeftSensor.Name = "rbLeftSensor";
            this.rbLeftSensor.TabStop = true;
            this.rbLeftSensor.UseVisualStyleBackColor = true;
            this.rbLeftSensor.CheckedChanged += new System.EventHandler(this.RbSensor_CheckedChanged);
            // 
            // label3
            // 
            this.label3.AccessibleDescription = null;
            this.label3.AccessibleName = null;
            resources.ApplyResources(this.label3, "label3");
            this.label3.Font = null;
            this.label3.Name = "label3";
            // 
            // nudCompareValue
            // 
            this.nudCompareValue.AccessibleDescription = null;
            this.nudCompareValue.AccessibleName = null;
            resources.ApplyResources(this.nudCompareValue, "nudCompareValue");
            this.nudCompareValue.BackColor = System.Drawing.Color.White;
            this.nudCompareValue.BackgroundImage = null;
            this.nudCompareValue.DecimalPlaces = 0;
            this.nudCompareValue.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudCompareValue.Maximum = new decimal(new int[] {
            100,
            0,
            0,
            0});
            this.nudCompareValue.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudCompareValue.Name = "nudCompareValue";
            this.nudCompareValue.Value = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudCompareValue.ValueChanged += new System.EventHandler(this.NudCompareValue_ValueChanged);
            // 
            // lValueHelp
            // 
            this.lValueHelp.AccessibleDescription = null;
            this.lValueHelp.AccessibleName = null;
            resources.ApplyResources(this.lValueHelp, "lValueHelp");
            this.lValueHelp.Name = "lValueHelp";
            // 
            // CompareLinePanel
            // 
            this.AccessibleDescription = null;
            this.AccessibleName = null;
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            resources.ApplyResources(this, "$this");
            this.BackgroundImage = null;
            this.Controls.Add(this.lValueHelp);
            this.Controls.Add(this.nudCompareValue);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.rbRightSensor);
            this.Controls.Add(this.rbLeftSensor);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.cbOperator);
            this.Controls.Add(this.cbCompareVariable);
            this.Name = "CompareLinePanel";
            this.Controls.SetChildIndex(this.lActionName, 0);
            this.Controls.SetChildIndex(this.cbCompareVariable, 0);
            this.Controls.SetChildIndex(this.cbOperator, 0);
            this.Controls.SetChildIndex(this.label1, 0);
            this.Controls.SetChildIndex(this.label2, 0);
            this.Controls.SetChildIndex(this.rbLeftSensor, 0);
            this.Controls.SetChildIndex(this.rbRightSensor, 0);
            this.Controls.SetChildIndex(this.label3, 0);
            this.Controls.SetChildIndex(this.nudCompareValue, 0);
            this.Controls.SetChildIndex(this.lValueHelp, 0);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private Moway.Template.Controls.MowayComboBox cbOperator;
        private Moway.Template.Controls.MowayComboBox cbCompareVariable;
        private Moway.Template.Controls.MowayRadioButton rbRightSensor;
        private Moway.Template.Controls.MowayRadioButton rbLeftSensor;
        private System.Windows.Forms.Label label3;
        private Moway.Template.Controls.MowayNumericUpDown nudCompareValue;
        private System.Windows.Forms.Label lValueHelp;
    }
}
