namespace Moway.Template.Controls
{
    partial class MowayNumericUpDown
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MowayNumericUpDown));
            this.bUp = new System.Windows.Forms.Button();
            this.bDown = new System.Windows.Forms.Button();
            this.timer = new System.Windows.Forms.Timer(this.components);
            this.textBox = new System.Windows.Forms.TextBox();
            this.SuspendLayout();
            // 
            // bUp
            // 
            this.bUp.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bUp.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(193)))), ((int)(((byte)(193)))), ((int)(((byte)(193)))));
            this.bUp.FlatAppearance.BorderSize = 0;
            this.bUp.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bUp.Image = ((System.Drawing.Image)(resources.GetObject("bUp.Image")));
            this.bUp.Location = new System.Drawing.Point(38, 1);
            this.bUp.Name = "bUp";
            this.bUp.Size = new System.Drawing.Size(11, 9);
            this.bUp.TabIndex = 1;
            this.bUp.TabStop = false;
            this.bUp.UseVisualStyleBackColor = false;
            this.bUp.MouseDown += new System.Windows.Forms.MouseEventHandler(this.BUp_MouseDown);
            this.bUp.MouseUp += new System.Windows.Forms.MouseEventHandler(this.BUp_MouseUp);
            // 
            // bDown
            // 
            this.bDown.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.bDown.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(193)))), ((int)(((byte)(193)))), ((int)(((byte)(193)))));
            this.bDown.FlatAppearance.BorderSize = 0;
            this.bDown.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bDown.Image = ((System.Drawing.Image)(resources.GetObject("bDown.Image")));
            this.bDown.Location = new System.Drawing.Point(38, 11);
            this.bDown.Name = "bDown";
            this.bDown.Size = new System.Drawing.Size(11, 9);
            this.bDown.TabIndex = 2;
            this.bDown.TabStop = false;
            this.bDown.UseVisualStyleBackColor = false;
            this.bDown.MouseDown += new System.Windows.Forms.MouseEventHandler(this.BDown_MouseDown);
            this.bDown.MouseUp += new System.Windows.Forms.MouseEventHandler(this.BDown_MouseUp);
            // 
            // timer
            // 
            this.timer.Interval = 500;
            this.timer.Tick += new System.EventHandler(this.Timer_Tick);
            // 
            // textBox
            // 
            this.textBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.textBox.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBox.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textBox.Location = new System.Drawing.Point(4, 2);
            this.textBox.MaxLength = 10;
            this.textBox.Name = "textBox";
            this.textBox.Size = new System.Drawing.Size(31, 14);
            this.textBox.TabIndex = 0;
            this.textBox.Text = "1";
            this.textBox.PreviewKeyDown += new System.Windows.Forms.PreviewKeyDownEventHandler(this.TextBox_PreviewKeyDown);
            this.textBox.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.TextBox_KeyPress);
            // 
            // MowayNumericUpDown
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.textBox);
            this.Controls.Add(this.bDown);
            this.Controls.Add(this.bUp);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "MowayNumericUpDown";
            this.Size = new System.Drawing.Size(50, 20);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button bUp;
        private System.Windows.Forms.Button bDown;
        private System.Windows.Forms.Timer timer;
        private System.Windows.Forms.TextBox textBox;
    }
}
