namespace Moway.Template.Controls
{
    partial class MowayHTrackBar
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.thumb = new Moway.Template.Controls.TrackThumb();
            this.SuspendLayout();
            // 
            // thumb
            // 
            this.thumb.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)));
            this.thumb.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(153)))), ((int)(((byte)(153)))), ((int)(((byte)(153)))));
            this.thumb.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(207)))), ((int)(((byte)(207)))));
            this.thumb.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.thumb.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.thumb.Location = new System.Drawing.Point(0, 3);
            this.thumb.Name = "thumb";
            this.thumb.Size = new System.Drawing.Size(20, 5);
            this.thumb.TabIndex = 0;
            this.thumb.UseVisualStyleBackColor = false;
            this.thumb.MouseMove += new System.Windows.Forms.MouseEventHandler(this.Thumb_MouseMove);
            this.thumb.MouseDown += new System.Windows.Forms.MouseEventHandler(this.Thumb_MouseDown);
            this.thumb.MouseUp += new System.Windows.Forms.MouseEventHandler(this.Thumb_MouseUp);
            // 
            // MowayHTrackBar
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(234)))), ((int)(((byte)(234)))));
            this.Controls.Add(this.thumb);
            this.Name = "MowayHTrackBar";
            this.Size = new System.Drawing.Size(80, 12);
            this.ResumeLayout(false);

        }

        #endregion

        private TrackThumb thumb;
    }
}
