namespace Moway.Template.Controls
{
    partial class MowayOnOff
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.bOff = new Moway.Template.Controls.OnOffButton();
            this.bOn = new Moway.Template.Controls.OnOffButton();
            this.SuspendLayout();
            // 
            // bOff
            // 
            this.bOff.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.bOff.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.bOff.FlatAppearance.BorderSize = 0;
            this.bOff.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(235)))), ((int)(((byte)(235)))));
            this.bOff.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(235)))), ((int)(((byte)(235)))));
            this.bOff.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bOff.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bOff.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.bOff.Location = new System.Drawing.Point(2, 25);
            this.bOff.Name = "bOff";
            this.bOff.Selected = false;
            this.bOff.Size = new System.Drawing.Size(36, 23);
            this.bOff.TabIndex = 1;
            this.bOff.Text = "Off";
            this.bOff.UseVisualStyleBackColor = false;
            this.bOff.Click += new System.EventHandler(this.BOff_Click);
            // 
            // bOn
            // 
            this.bOn.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.bOn.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(207)))), ((int)(((byte)(207)))));
            this.bOn.FlatAppearance.BorderSize = 0;
            this.bOn.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(207)))), ((int)(((byte)(207)))));
            this.bOn.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(207)))), ((int)(((byte)(207)))));
            this.bOn.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bOn.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bOn.ForeColor = System.Drawing.SystemColors.ControlText;
            this.bOn.Location = new System.Drawing.Point(2, 2);
            this.bOn.Name = "bOn";
            this.bOn.Selected = true;
            this.bOn.Size = new System.Drawing.Size(36, 23);
            this.bOn.TabIndex = 0;
            this.bOn.Text = "On";
            this.bOn.UseVisualStyleBackColor = false;
            this.bOn.Click += new System.EventHandler(this.BOn_Click);
            // 
            // MowayOnOff
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.Controls.Add(this.bOff);
            this.Controls.Add(this.bOn);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "MowayOnOff";
            this.Size = new System.Drawing.Size(40, 50);
            this.ResumeLayout(false);

        }

        #endregion

        private OnOffButton bOn;
        private OnOffButton bOff;


    }
}
