namespace Moway.Template.Controls
{
    partial class SharePanelSelector
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.lText = new System.Windows.Forms.Label();
            this.toolTip = new Moway.Template.Controls.MowayToolTip();
            this.SuspendLayout();
            // 
            // lText
            // 
            this.lText.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.lText.Location = new System.Drawing.Point(7, 5);
            this.lText.Name = "lText";
            this.lText.Size = new System.Drawing.Size(86, 19);
            this.lText.TabIndex = 0;
            this.lText.Text = "Text";
            this.lText.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            this.lText.Click += new System.EventHandler(this.LText_Click);
            // 
            // ShareTabButton
            // 
            this.Controls.Add(this.lText);
            this.Name = "ShareBoxButton";
            this.Size = new System.Drawing.Size(100, 30);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Label lText;
        private MowayToolTip toolTip;
    }
}
