namespace Moway.Project.GraphicProject.Actions.AssignSpeed
{
    partial class AssignSpeedPanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AssignSpeedPanel));
            this.lVariable = new System.Windows.Forms.Label();
            this.cbAssignVariable = new Moway.Template.Controls.MowayComboBox();
            this.rbRightSpeed = new Moway.Template.Controls.MowayRadioButton();
            this.rbLeftSpeed = new Moway.Template.Controls.MowayRadioButton();
            this.label1 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // lActionName
            // 
            resources.ApplyResources(this.lActionName, "lActionName");
            // 
            // lVariable
            // 
            resources.ApplyResources(this.lVariable, "lVariable");
            this.lVariable.Name = "lVariable";
            // 
            // cbAssignVariable
            // 
            this.cbAssignVariable.BackColor = System.Drawing.Color.White;
            this.cbAssignVariable.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbAssignVariable.DropDownHeight = 100;
            this.cbAssignVariable.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            resources.ApplyResources(this.cbAssignVariable, "cbAssignVariable");
            this.cbAssignVariable.FormattingEnabled = true;
            this.cbAssignVariable.Name = "cbAssignVariable";
            this.cbAssignVariable.SelectedIndexChanged += new System.EventHandler(this.CbAssignVariable_SelectedIndexChanged);
            // 
            // rbRightSpeed
            // 
            resources.ApplyResources(this.rbRightSpeed, "rbRightSpeed");
            this.rbRightSpeed.Checked = true;
            this.rbRightSpeed.Name = "rbRightSpeed";
            this.rbRightSpeed.TabStop = true;
            this.rbRightSpeed.UseVisualStyleBackColor = true;
            this.rbRightSpeed.CheckedChanged += new System.EventHandler(this.RbSpeed_CheckedChanged);
            // 
            // rbLeftSpeed
            // 
            resources.ApplyResources(this.rbLeftSpeed, "rbLeftSpeed");
            this.rbLeftSpeed.Name = "rbLeftSpeed";
            this.rbLeftSpeed.TabStop = true;
            this.rbLeftSpeed.UseVisualStyleBackColor = true;
            this.rbLeftSpeed.CheckedChanged += new System.EventHandler(this.RbSpeed_CheckedChanged);
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // AssignSpeedPanel
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.label1);
            this.Controls.Add(this.lVariable);
            this.Controls.Add(this.cbAssignVariable);
            this.Controls.Add(this.rbRightSpeed);
            this.Controls.Add(this.rbLeftSpeed);
            this.Name = "AssignSpeedPanel";
            resources.ApplyResources(this, "$this");
            this.Controls.SetChildIndex(this.lActionName, 0);
            this.Controls.SetChildIndex(this.rbLeftSpeed, 0);
            this.Controls.SetChildIndex(this.rbRightSpeed, 0);
            this.Controls.SetChildIndex(this.cbAssignVariable, 0);
            this.Controls.SetChildIndex(this.lVariable, 0);
            this.Controls.SetChildIndex(this.label1, 0);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label lVariable;
        private Moway.Template.Controls.MowayComboBox cbAssignVariable;
        private Moway.Template.Controls.MowayRadioButton rbRightSpeed;
        private Moway.Template.Controls.MowayRadioButton rbLeftSpeed;
        private System.Windows.Forms.Label label1;
    }
}
