namespace Moway.Simulator.Registers
{
    partial class RegisterListViewItem
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.lValue = new System.Windows.Forms.Label();
            this.lName = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // lValue
            // 
            this.lValue.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.lValue.Location = new System.Drawing.Point(100, 0);
            this.lValue.Name = "lValue";
            this.lValue.Size = new System.Drawing.Size(60, 18);
            this.lValue.TabIndex = 0;
            this.lValue.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lValue.Click += new System.EventHandler(this.RegisterListViewItem_Click);
            // 
            // lName
            // 
            this.lName.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.lName.Location = new System.Drawing.Point(0, 0);
            this.lName.Name = "lName";
            this.lName.Size = new System.Drawing.Size(98, 18);
            this.lName.TabIndex = 1;
            this.lName.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lName.Click += new System.EventHandler(this.RegisterListViewItem_Click);
            // 
            // RegisterListViewItem
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.lName);
            this.Controls.Add(this.lValue);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "RegisterListViewItem";
            this.Size = new System.Drawing.Size(160, 18);
            this.Click += new System.EventHandler(this.RegisterListViewItem_Click);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Label lValue;
        private System.Windows.Forms.Label lName;
    }
}
