namespace Moway.Project.GraphicProject.Actions.StartRf
{
    partial class StartRfPanel
    {
        /// <summary> 
        /// Variable of the designer required.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean the resources that are being used.
        /// </summary>
        /// <param name="disposing">true if the managed resources should be removed; false otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the Component Designer

        /// <summary> 
        /// Method necessary to support the Designer. It can not be modified 
        /// the content of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(StartRfPanel));
            this.nudChanel = new Moway.Template.Controls.MowayNumericUpDown();
            this.lChanel = new System.Windows.Forms.Label();
            this.nudDirection = new Moway.Template.Controls.MowayNumericUpDown();
            this.lDirection = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.lRange0 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // lActionName
            // 
            resources.ApplyResources(this.lActionName, "lActionName");
            // 
            // nudChanel
            // 
            this.nudChanel.BackColor = System.Drawing.Color.White;
            this.nudChanel.DecimalPlaces = 0;
            resources.ApplyResources(this.nudChanel, "nudChanel");
            this.nudChanel.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudChanel.Maximum = new decimal(new int[] {
            127,
            0,
            0,
            0});
            this.nudChanel.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudChanel.Name = "nudChanel";
            this.nudChanel.Value = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudChanel.ValueChanged += new System.EventHandler(this.NudChanel_ValueChanged);
            // 
            // lChanel
            // 
            resources.ApplyResources(this.lChanel, "lChanel");
            this.lChanel.Name = "lChanel";
            // 
            // nudDirection
            // 
            this.nudDirection.BackColor = System.Drawing.Color.White;
            this.nudDirection.DecimalPlaces = 0;
            resources.ApplyResources(this.nudDirection, "nudDirection");
            this.nudDirection.Increment = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudDirection.Maximum = new decimal(new int[] {
            255,
            0,
            0,
            0});
            this.nudDirection.Minimum = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.nudDirection.Name = "nudDirection";
            this.nudDirection.Value = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nudDirection.Load += new System.EventHandler(this.NudDirection_ValueChanged);
            this.nudDirection.ValueChanged += new System.EventHandler(this.NudDirection_ValueChanged);
            // 
            // lDirection
            // 
            resources.ApplyResources(this.lDirection, "lDirection");
            this.lDirection.Name = "lDirection";
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // lRange0
            // 
            resources.ApplyResources(this.lRange0, "lRange0");
            this.lRange0.Name = "lRange0";
            // 
            // StartRfPanel
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.label1);
            this.Controls.Add(this.lRange0);
            this.Controls.Add(this.nudChanel);
            this.Controls.Add(this.nudDirection);
            this.Controls.Add(this.lChanel);
            this.Controls.Add(this.lDirection);
            resources.ApplyResources(this, "$this");
            this.Name = "StartRfPanel";
            this.Controls.SetChildIndex(this.lDirection, 0);
            this.Controls.SetChildIndex(this.lChanel, 0);
            this.Controls.SetChildIndex(this.lActionName, 0);
            this.Controls.SetChildIndex(this.nudDirection, 0);
            this.Controls.SetChildIndex(this.nudChanel, 0);
            this.Controls.SetChildIndex(this.lRange0, 0);
            this.Controls.SetChildIndex(this.label1, 0);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Moway.Template.Controls.MowayNumericUpDown nudChanel;
        private System.Windows.Forms.Label lChanel;
        private Moway.Template.Controls.MowayNumericUpDown nudDirection;
        private System.Windows.Forms.Label lDirection;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label lRange0;
    }
}
